<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Job teitle</name>
   <tag></tag>
   <elementGuidId>4bbd156c-7fb9-4b92-a005-a4515045cae1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.-ol-link.b-expanded-tooltip._text_ellipsis</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='job_21297989']/td[4]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ed9ff608-4da1-483c-bf5e-1a7390edb939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>186fb836-33df-486d-b8ab-3a044bbf89c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en/job/undefined/company-name/job-teitle/50555b533eca12b2ec5fe8ccc32c163b</value>
      <webElementGuid>a9d7c6d0-f292-474e-98b8-6bc455398984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Job teitle</value>
      <webElementGuid>44007b51-2779-480a-ae01-1a74233850dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>-ol-link b-expanded-tooltip _text_ellipsis</value>
      <webElementGuid>12ce06c1-5da9-410c-ae14-fae5e89fc7a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Job teitle                    </value>
      <webElementGuid>b862fb12-5ea8-46e2-8019-75a2e0a305f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;job_21297989&quot;)/td[@class=&quot;b-company-admin-panel-table__cell&quot;]/div[@class=&quot;b-company-admin-panel-table__data-text&quot;]/a[@class=&quot;-ol-link b-expanded-tooltip _text_ellipsis&quot;]</value>
      <webElementGuid>5d00034a-6d4e-4603-b842-baee9ba57e52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='job_21297989']/td[4]/div/a</value>
      <webElementGuid>543925af-3693-400f-a75e-1a5e69255b55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Job teitle')]</value>
      <webElementGuid>29b182e0-50fa-4f96-8386-012a9f19798a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test'])[1]/following::a[1]</value>
      <webElementGuid>e38e4b32-cbb4-4cd5-994f-46e312777c72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings'])[4]/following::a[1]</value>
      <webElementGuid>8b5ba803-2064-4fd2-a26e-3893fa3cd415</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Online'])[3]/preceding::a[1]</value>
      <webElementGuid>e9b8d2b8-f90a-47cb-80f9-d0a70bc41d46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='of'])[1]/preceding::a[2]</value>
      <webElementGuid>ec37ed8a-94d9-4d30-96ff-fe7d33850eaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Job teitle']/parent::*</value>
      <webElementGuid>3dd10bb8-d643-4d73-8a8b-2c13f45dc9f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/en/job/undefined/company-name/job-teitle/50555b533eca12b2ec5fe8ccc32c163b')]</value>
      <webElementGuid>eb4b6612-0441-43f3-b1a9-c4182a1dae17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div/a</value>
      <webElementGuid>0b7cb14e-a080-4467-a5d6-874455a49c6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/en/job/undefined/company-name/job-teitle/50555b533eca12b2ec5fe8ccc32c163b' and @title = 'Job teitle' and (text() = 'Job teitle                    ' or . = 'Job teitle                    ')]</value>
      <webElementGuid>a6bad3c0-aae9-4c74-b674-f21eeb9b3936</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
