<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_City  Country_input_city_country</name>
   <tag></tag>
   <elementGuidId>314820cc-61cf-4f7d-be03-2a0f68966b1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='location']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#location</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9daa5f2f-715e-4923-b532-14842c6cb903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>location</value>
      <webElementGuid>34fbc025-c9a8-4b73-acbd-b6d46448a76f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cf66dd1a-3d38-44c0-b752-00f7a2ec6d43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input_city_country</value>
      <webElementGuid>8a752bbd-8dad-4c6b-b7f5-4f55347832a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>City &amp; Country</value>
      <webElementGuid>1faa6c8c-7be1-485d-beb9-af92c3c425e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-field pac-target-input</value>
      <webElementGuid>2a849d53-443e-4d12-a1fd-6b488f602750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4bbf558e-4103-43f1-b836-c1beacf63df9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;location&quot;)</value>
      <webElementGuid>42cf1495-26cc-49b0-b0fb-ef97279e52e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='location']</value>
      <webElementGuid>9ea245b8-78bd-4836-b18e-9968f8c5d98d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-checkout']/div/div/div/div/div[3]/div[4]/div[2]/input</value>
      <webElementGuid>5ea3b1bf-7ad9-4ae3-a738-8f53739695b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/input</value>
      <webElementGuid>0c5ee4ae-ab09-4607-84b8-63017f8055de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'location' and @type = 'text' and @name = 'input_city_country' and @placeholder = 'City &amp; Country']</value>
      <webElementGuid>b31d5f41-6e92-404d-a7d6-1aefb9193911</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
