<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select number</name>
   <tag></tag>
   <elementGuidId>06865adb-d239-49bd-b78c-757516c702cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-input_number_of_employee-hy-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@data-select2-id='13']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dac9c86e-e2d0-4099-a9e4-112cb3817c94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>278a9e11-53e8-4e18-957c-cf481dbdcf4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-input_number_of_employee-hy-container</value>
      <webElementGuid>56eb80d3-9e89-4542-8e74-a8c4c6ae21c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>154db10e-0903-42ac-ba5a-1d6f806feeaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6c1b5fc7-f2b2-4860-9c9c-513993fef701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select number</value>
      <webElementGuid>d7f36f61-74ef-4aea-bc01-a8f14ab86062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-input_number_of_employee-hy-container&quot;)</value>
      <webElementGuid>ce0a068b-5b28-45ed-a1b0-f797da64e51f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-input_number_of_employee-hy-container']</value>
      <webElementGuid>448968dc-330f-4abe-beb4-9f462ad696d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-checkout']/div/div/div/div/div[3]/div[7]/div[2]/span/span/span/span</value>
      <webElementGuid>f34e29da-ab29-4379-b9aa-71ab80d35ad2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select communication language'])[2]/following::span[7]</value>
      <webElementGuid>296aa927-2ae6-440c-9bfb-c4bf9a1b7c4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registration Error'])[1]/preceding::span[5]</value>
      <webElementGuid>96468461-3a57-4fe2-a2ed-4ada32d66c38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/span/span/span</value>
      <webElementGuid>b2649cb0-bb5b-4bd5-ada4-7e1f54749e7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-input_number_of_employee-hy-container' and (text() = 'Select number' or . = 'Select number')]</value>
      <webElementGuid>33db308c-861b-4443-8929-9edff743c12e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
