<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select communication language</name>
   <tag></tag>
   <elementGuidId>b7191bf7-facb-4c11-99a1-100b757209f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-input_communication_language-mj-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@data-select2-id='10']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>28849379-1b9f-4436-a69b-bbde8f97e13d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>1991d41a-fc35-4118-ba3a-0f51ee25aaae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-input_communication_language-mj-container</value>
      <webElementGuid>503de726-6212-40cd-8467-c2b93e65b370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>e654474c-6077-4060-954a-c007553160e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1dbe3047-225a-4185-b154-e18e307c8031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select communication language</value>
      <webElementGuid>45c56f65-7b4d-4698-8e6a-d01ebdda5fe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-input_communication_language-mj-container&quot;)</value>
      <webElementGuid>cfe4a022-ab36-42cc-99fd-dd6f7166a558</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-input_communication_language-mj-container']</value>
      <webElementGuid>6e4149ce-3be5-4cd0-9656-379faa328ca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-checkout']/div/div/div/div/div[3]/div[7]/div/span/span/span/span</value>
      <webElementGuid>57aae447-5ac2-4919-a708-e2d00b6844ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administration'])[2]/following::span[8]</value>
      <webElementGuid>3e50d150-15cb-403c-9608-de885d61f33f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/span/span/span/span</value>
      <webElementGuid>ab3db474-ad99-4f8c-b814-b583917a5237</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-input_communication_language-mj-container' and (text() = 'Select communication language' or . = 'Select communication language')]</value>
      <webElementGuid>4654c026-80b0-40cc-91cb-088d14dcbcb3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
