<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Job url</name>
   <tag></tag>
   <elementGuidId>9d1f8883-1fd9-45d3-83df-dbcc0d98cfe4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='job_21297937']/td[4]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.-ol-link.b-expanded-tooltip._text_ellipsis</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2475cf31-9704-4ddb-a52c-543dc926a9a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>99cd1314-bb11-47fc-b428-5df0db64eb5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en/job/undefined/test/job-url/fe311bde527efb356a62228e26d1415c</value>
      <webElementGuid>454cd688-9c4a-4c4c-b7c5-84907a33f6e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Job url</value>
      <webElementGuid>fd9f89f0-068e-4e7a-8958-ceb5f5681b25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>-ol-link b-expanded-tooltip _text_ellipsis</value>
      <webElementGuid>fe7f29c4-f84b-4cf3-ba82-379bc708fd6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Job url                    </value>
      <webElementGuid>26adccd0-477c-4068-9a5c-dc0003ff84dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;job_21297937&quot;)/td[@class=&quot;b-company-admin-panel-table__cell&quot;]/div[@class=&quot;b-company-admin-panel-table__data-text&quot;]/a[@class=&quot;-ol-link b-expanded-tooltip _text_ellipsis&quot;]</value>
      <webElementGuid>307049f6-9d15-4337-abdd-c3a712aa1056</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='job_21297937']/td[4]/div/a</value>
      <webElementGuid>395311d6-9fbb-41b3-9642-945d9570760d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Job url')]</value>
      <webElementGuid>e2f81544-4998-41a8-99fa-63c200a476ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='fe311bde527efb356a62228e26d1415c'])[1]/following::a[1]</value>
      <webElementGuid>e85afeb3-47f5-4f60-8014-45b8c4552ff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings'])[4]/following::a[1]</value>
      <webElementGuid>b543b11e-4ab5-4494-934e-6b44da219747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Online'])[3]/preceding::a[1]</value>
      <webElementGuid>65addf58-a670-4491-89cf-18239c98dd6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='of'])[1]/preceding::a[2]</value>
      <webElementGuid>fbc5119e-38ec-4dcc-b8d6-2defcaac661d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Job url']/parent::*</value>
      <webElementGuid>0e10d2d6-3e76-4be0-bdc8-ad3eedd46ce1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/en/job/undefined/test/job-url/fe311bde527efb356a62228e26d1415c')]</value>
      <webElementGuid>3ee5cd61-f611-4150-82ad-aa4568a78aba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div/a</value>
      <webElementGuid>c331e4f5-f9ba-45e7-88b9-fe6798ea89be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/en/job/undefined/test/job-url/fe311bde527efb356a62228e26d1415c' and @title = 'Job url' and (text() = 'Job url                    ' or . = 'Job url                    ')]</value>
      <webElementGuid>3d280ab6-1dc7-4916-b8e5-f4da9d1c6661</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
