<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Job url</name>
   <tag></tag>
   <elementGuidId>9d1f8883-1fd9-45d3-83df-dbcc0d98cfe4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.-ol-link.b-expanded-tooltip._text_ellipsis</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr/td[4]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6612e153-0bb1-4863-9381-0cfe66474e30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>0ed8952a-2581-4271-9062-64c73a85b2b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en/job/undefined/test/job-url/fe311bde527efb356a62228e26d1415c</value>
      <webElementGuid>04df76f5-8414-42cd-997a-9f54f34a7b0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Job url</value>
      <webElementGuid>fe4f866d-4efa-4711-b2fc-43496f5badc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>-ol-link b-expanded-tooltip _text_ellipsis</value>
      <webElementGuid>90f74640-a161-459f-8977-6d3f31df22be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Job url                    </value>
      <webElementGuid>6f374849-cd3a-4150-9079-15e27760f425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;job_21297937&quot;)/td[@class=&quot;b-company-admin-panel-table__cell&quot;]/div[@class=&quot;b-company-admin-panel-table__data-text&quot;]/a[@class=&quot;-ol-link b-expanded-tooltip _text_ellipsis&quot;]</value>
      <webElementGuid>89d4010e-099f-47e4-b736-ff492e30eb9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='job_21297937']/td[4]/div/a</value>
      <webElementGuid>f64d1ac6-13a2-49c7-a742-02c3cd55bfaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Job url')]</value>
      <webElementGuid>5f6b5036-4c17-458c-a5c4-a2d295219bbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='fe311bde527efb356a62228e26d1415c'])[1]/following::a[1]</value>
      <webElementGuid>62f0a168-edce-4bed-a84d-2b944636ba86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings'])[4]/following::a[1]</value>
      <webElementGuid>a8b79838-1f6e-49cc-8f90-f0a1eb347551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Online'])[3]/preceding::a[1]</value>
      <webElementGuid>95067f3e-f40c-49de-a452-cf6bbb87e963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='of'])[1]/preceding::a[2]</value>
      <webElementGuid>b7109cf4-93b8-4111-8928-0ea051e1a5b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Job url']/parent::*</value>
      <webElementGuid>d0a51003-c457-4715-8fdc-97f16ccf4193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/en/job/undefined/test/job-url/fe311bde527efb356a62228e26d1415c')]</value>
      <webElementGuid>41448d86-ec17-4529-b2e0-922b60ebe1ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div/a</value>
      <webElementGuid>9ed92b2c-92e3-42fe-80e0-0ba237138d90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/en/job/undefined/test/job-url/fe311bde527efb356a62228e26d1415c' and @title = 'Job url' and (text() = 'Job url                    ' or . = 'Job url                    ')]</value>
      <webElementGuid>63fd3b69-29d4-494b-9f7c-c9f2fa7c682e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
