<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Select</name>
   <tag></tag>
   <elementGuidId>cd4d6ae5-1969-4421-90ac-be247f2972d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.b-package-box__btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@class='b-package-box__btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ad20c74d-8bff-43ac-aebc-afe8b089028e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>b-package-box__btn</value>
      <webElementGuid>33d7be6f-1af9-4d4b-b122-9a020cbc6b01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                        Select
                                                    </value>
      <webElementGuid>dd77d8d2-fbe9-4f9b-8f8c-85f78bca5e17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;package_item_427&quot;)/div[@class=&quot;b-package-box&quot;]/form[1]/button[@class=&quot;b-package-box__btn&quot;]</value>
      <webElementGuid>7bb8f2ff-197b-4ec5-9194-ef02416c6044</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='package_item_427']/div/form/button</value>
      <webElementGuid>34d41883-a010-4d6b-aecf-040006ad0d21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jobs Available:'])[1]/following::button[1]</value>
      <webElementGuid>5af80a93-8855-48ee-8b29-56f66284c968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jobs Posted:'])[1]/following::button[1]</value>
      <webElementGuid>518cc0d5-9706-4d7c-bbfb-ccb854d4f061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/preceding::button[1]</value>
      <webElementGuid>ebc6324b-2b56-480c-acda-d604ba0e1f6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>111f04df-9874-436d-bc5e-27f4e5b04d73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '
                                                        Select
                                                    ' or . = '
                                                        Select
                                                    ')]</value>
      <webElementGuid>690fe08c-1e9a-4c49-b755-9305258ca120</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
