<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_I am looking for a job_input_job</name>
   <tag></tag>
   <elementGuidId>678dc9d2-06fb-405b-9eb8-10b3ff0a627c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='input_job']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;input_job&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>0d58f201-3ea0-443d-90ad-5f172d7170ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-field</value>
      <webElementGuid>ade0e889-a6a7-4c41-8907-c1042bfa24ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input_job</value>
      <webElementGuid>9d91547a-3262-4b78-a57f-bcd269d05509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Describe the job you're looking for. For example: I am looking for a job as cook/warehouse worker/designer.</value>
      <webElementGuid>68f7aae1-1368-4bd8-b848-ca553a54ad21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;premium-jobseeker-form&quot;)/div[@class=&quot;form-group-global display--flex flex--wrap p-sides&quot;]/textarea[@class=&quot;input-field&quot;]</value>
      <webElementGuid>3d476a0a-71c4-486d-ba5c-0da254890684</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='input_job']</value>
      <webElementGuid>0aa3cdd5-4bfe-4a23-b02f-47cc920ba5da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='premium-jobseeker-form']/div[3]/textarea</value>
      <webElementGuid>e89229ef-771b-49f5-b380-bb26269c61e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>890dff54-ec9f-4bdb-9d09-da541fa4dc36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'input_job' and @placeholder = concat(&quot;Describe the job you&quot; , &quot;'&quot; , &quot;re looking for. For example: I am looking for a job as cook/warehouse worker/designer.&quot;)]</value>
      <webElementGuid>24449ae8-ca40-4c99-a692-4b65493f0637</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
