<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Password_hide-icon password_hidden</name>
   <tag></tag>
   <elementGuidId>ea212665-19de-47b3-b207-3d6a4d79232f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.hide-icon.password_hidden</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='Employer-information']/div/div/div/div/div[3]/div/div[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c292868f-d916-4a89-8cae-183f60d2de3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/images/icon/hide.svg</value>
      <webElementGuid>98c7f610-b3c8-49c6-813c-74a8f6f8b9a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hide-icon password_hidden</value>
      <webElementGuid>18e8c73e-f0d1-492a-b889-c3b25daaab09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Employer-information&quot;)/div[@class=&quot;order-detail-inner display--flex flex--wrap&quot;]/div[@class=&quot;order-detail-left&quot;]/div[@class=&quot;order-detail-left-inner&quot;]/div[@class=&quot;top&quot;]/div[@class=&quot;order-detail-form&quot;]/div[@class=&quot;form-group display--flex flex--wrap align-item--center name-email&quot;]/div[@class=&quot;form-inner display--flex flex--wrap align-item--center password-input&quot;]/img[@class=&quot;hide-icon password_hidden&quot;]</value>
      <webElementGuid>079d900a-60ae-4c04-af92-f02c99b38e55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='Employer-information']/div/div/div/div/div[3]/div/div[2]/img</value>
      <webElementGuid>39d0f068-a6dd-4153-85ed-6627982121e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>96c41931-5e30-4017-bab8-b0ff9efc5724</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/images/icon/hide.svg']</value>
      <webElementGuid>fb21916a-e10a-47d1-857c-021a35d0ce2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
