<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Publish</name>
   <tag></tag>
   <elementGuidId>44a5afe2-ea3d-40a4-82e0-421f143c8043</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-card-verify']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn-card-verify</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2290d561-355c-4a64-bbc6-a5e781e46d67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-dark</value>
      <webElementGuid>55a225ce-5bea-49dd-8685-25c515f6b75e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-card-verify</value>
      <webElementGuid>66754904-24fc-4519-a0a7-32781c1a3994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-text-loading</name>
      <type>Main</type>
      <value>LOADING</value>
      <webElementGuid>1e90a1cc-d1bf-41b9-a513-05afe9a2109b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Publish</value>
      <webElementGuid>6cd3c2fc-e598-4f62-9b39-21be99b9217b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-card-verify&quot;)</value>
      <webElementGuid>3e65c8ca-7dda-49e9-8c2b-c2937beba1c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-card-verify']</value>
      <webElementGuid>f29a8c49-49e5-4a0c-bb8f-dcbe949d7d8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-checkout']/div/div/div[2]/div/div[2]/button</value>
      <webElementGuid>dfad6d8f-1efb-492d-9d37-0e985f302900</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel Profile'])[1]/following::button[1]</value>
      <webElementGuid>20bf97dd-fa3b-46aa-9486-37526690de7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error'])[1]/following::button[1]</value>
      <webElementGuid>f124610d-569e-4143-9032-fe10c8c5b8b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order summary'])[1]/preceding::button[1]</value>
      <webElementGuid>5806706d-b777-4bd7-82a9-8cd346fb43ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product'])[2]/preceding::button[1]</value>
      <webElementGuid>26c022d8-caf0-4050-9bb1-7beab8aafcf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Publish']/parent::*</value>
      <webElementGuid>27e01c76-e867-4e53-9f36-ee84de6d0159</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>42956a5d-fdbb-45c5-919b-52c5e614bba8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn-card-verify' and (text() = 'Publish' or . = 'Publish')]</value>
      <webElementGuid>14b20ab8-d422-4ea0-8e85-9a44e6496c67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
