<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last name_input_lastname</name>
   <tag></tag>
   <elementGuidId>1455c497-c1f4-4166-a697-fc26052ae5cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='input_lastname']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;input_lastname&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e28a7ec8-f1b9-4b29-a68b-b78d3463fd1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f798c8b1-d7b9-4ef5-9cc1-7ea00fbb7c91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input_lastname</value>
      <webElementGuid>23408a02-cbbb-479b-a50f-0cd27a423180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Last name</value>
      <webElementGuid>f77c1743-2eba-4ccc-815f-616e63d7715c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-field</value>
      <webElementGuid>e69cfb37-bc61-4075-a94b-20c880a42cf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;premium-jobseeker-form&quot;)/div[@class=&quot;form-group-global display--flex flex--wrap&quot;]/div[@class=&quot;form-inner display--flex flex--wrap align-item--center&quot;]/input[@class=&quot;input-field&quot;]</value>
      <webElementGuid>e18f6f54-da22-4933-bdf9-32fc8d24a844</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='input_lastname']</value>
      <webElementGuid>c5b452e8-9745-4507-ae1b-7e2146c11080</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='premium-jobseeker-form']/div[2]/div[2]/input</value>
      <webElementGuid>a6ff2d36-0bd8-4025-8843-9888e657613e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>97b428a8-0437-4e7a-b065-101a062a0b24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'input_lastname' and @placeholder = 'Last name']</value>
      <webElementGuid>8d2c3a9a-88c2-437a-8307-49920616e4fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
