<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_I am looking for a job_input_job</name>
   <tag></tag>
   <elementGuidId>831b0309-22a6-433d-90d0-d6644872cc44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='input_job']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;input_job&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>ca979c56-0c53-4fbe-b3fe-cfa3603c9b9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-field</value>
      <webElementGuid>ff1b89bb-dc44-4f3e-9604-6580bb564509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input_job</value>
      <webElementGuid>a4e59024-5102-4d9f-8b2d-709ba6230fa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Describe the job you're looking for. For example: I am looking for a job as cook/warehouse worker/designer.</value>
      <webElementGuid>a778c503-d8ed-459e-a89e-e0969a2f584d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;premium-jobseeker-form&quot;)/div[@class=&quot;form-group-global display--flex flex--wrap p-sides&quot;]/textarea[@class=&quot;input-field&quot;]</value>
      <webElementGuid>eae8f2ae-aeab-4f34-80f9-42bac50afde1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='input_job']</value>
      <webElementGuid>404a0a76-ffc2-4afc-a56f-ad455e3aa8c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='premium-jobseeker-form']/div[4]/textarea</value>
      <webElementGuid>b59e6dd6-8bec-40d2-ae5a-f453b2655e8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>f5f68b43-88df-402c-94de-4f6be79b765e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'input_job' and @placeholder = concat(&quot;Describe the job you&quot; , &quot;'&quot; , &quot;re looking for. For example: I am looking for a job as cook/warehouse worker/designer.&quot;)]</value>
      <webElementGuid>15fae4dd-1748-4b9a-9a40-3114e4f39d5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
