<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Password_a-h3r01h7n1lsq</name>
   <tag></tag>
   <elementGuidId>3ad5f153-4a09-406c-afb9-8906e3837203</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-h3r01h7n1lsq']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-h3r01h7n1lsq&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>4129464b-4ce3-4714-b592-f88a0df7bbe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>8407803d-35c3-46f3-be9c-45e485f4e2cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LfiRzcaAAAAAF18-SQqrsovqK5dd4V8T1rgfpyC&amp;co=aHR0cHM6Ly93d3cuam9ic3RvZGF5LndvcmxkOjQ0Mw..&amp;hl=en&amp;v=iZWPJyR27lB0cR4hL_xOX0GC&amp;size=normal&amp;cb=5z8s0mghpxtw</value>
      <webElementGuid>2a3ed010-3c56-491b-9041-ef0ff9ef03ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>19cdd964-7bb3-4f7a-ab31-00337b99f63a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>c3916878-c6a0-44cd-8340-1f8d9231eaba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>96e417cc-dde8-4132-b037-4a09657cef24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-h3r01h7n1lsq</value>
      <webElementGuid>b2ecc646-3946-4dde-8134-e4f550963411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b4340423-836c-4d3a-a1d5-7b3d76744a0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>c1e25ed4-d3d7-4452-b8fe-9dd6ae608f5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>25ca4654-3f23-4e88-aa41-fdfd5614676a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g-recaptcha&quot;)/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>d1ba30b1-cf9e-427d-ab18-adc4a76a7df1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-h3r01h7n1lsq']</value>
      <webElementGuid>7bd92b6f-7006-43dc-b82b-9e910377f0b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='g-recaptcha']/div/div/iframe</value>
      <webElementGuid>db718b0d-a262-4a88-bf31-45df3e44242c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>496b5cbf-a6c7-4d04-b3a2-73c438225c2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LfiRzcaAAAAAF18-SQqrsovqK5dd4V8T1rgfpyC&amp;co=aHR0cHM6Ly93d3cuam9ic3RvZGF5LndvcmxkOjQ0Mw..&amp;hl=en&amp;v=iZWPJyR27lB0cR4hL_xOX0GC&amp;size=normal&amp;cb=5z8s0mghpxtw' and @name = 'a-h3r01h7n1lsq']</value>
      <webElementGuid>f4ce08dc-f0d5-4d29-8993-c70663952c26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
