<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View Job</name>
   <tag></tag>
   <elementGuidId>cdedc014-0a8d-497c-b7f6-aa24f7cbb227</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn_from_viewjob</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//tbody /tr /td[4])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ea3b5293-2177-4984-a7a3-89dfda3fe5f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en/job/advertising/software-tester-job-city-of-manila/8c8bc8fd0e50ad66d8145c16e4df5137/</value>
      <webElementGuid>6981bddd-ff6a-4a6e-9402-ed4fbd5e2752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn_from_viewjob</value>
      <webElementGuid>2dedd491-bee4-42d5-95e5-ce079047c2a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Job</value>
      <webElementGuid>d98e2ae2-2b67-4aad-a892-1b876a81a1df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myform-p-2&quot;)/div[@class=&quot;actions clearfix&quot;]/ul[1]/li[1]/a[@class=&quot;btn_from_viewjob&quot;]</value>
      <webElementGuid>85cf120d-e9aa-48a0-8273-d05cd3208d80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='myform-p-2']/div[2]/ul/li/a</value>
      <webElementGuid>353c847b-1efc-46e8-9fa8-102263079d9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View Job')]</value>
      <webElementGuid>338af3d3-7bb6-405e-a86c-53225e8e8717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You have successfully posted your Job'])[1]/following::a[1]</value>
      <webElementGuid>e8be6000-844b-493b-a855-7bd93ea31b5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel post'])[2]/following::a[1]</value>
      <webElementGuid>7a2aab8c-6de9-498a-a140-576e84d1e831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Post another Job'])[1]/preceding::a[1]</value>
      <webElementGuid>b2f1e216-4379-42a9-a434-648469982561</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure you want to cancel your Job post?'])[1]/preceding::a[1]</value>
      <webElementGuid>74179e12-463d-4e21-90a0-bb8872b06193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View Job']/parent::*</value>
      <webElementGuid>85acf8ea-94ce-4bb8-801e-725903642ea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/en/job/advertising/software-tester-job-city-of-manila/8c8bc8fd0e50ad66d8145c16e4df5137/')]</value>
      <webElementGuid>5ec04490-6321-4ec5-ab27-c8039aea3f60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div[2]/ul/li/a</value>
      <webElementGuid>ca3199cd-fb17-4b81-87ce-617b9948eb7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/en/job/advertising/software-tester-job-city-of-manila/8c8bc8fd0e50ad66d8145c16e4df5137/' and (text() = 'View Job' or . = 'View Job')]</value>
      <webElementGuid>70905844-99a7-418e-b405-01dd56dfe2b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
