<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_RA-AT-2022-09-0014_privacy</name>
   <tag></tag>
   <elementGuidId>0aa0d11e-4f84-4f15-9f50-dc6c3cf48675</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#privacy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='privacy']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>077438e0-9685-46d5-9ac3-861a79852462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>848fd4c3-c824-4629-ad7f-682b89aab26b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>privacy</value>
      <webElementGuid>fd2d157d-a755-4313-a048-117aa85557c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>privacy</value>
      <webElementGuid>6c439ca1-fbdb-4cc1-a875-bb0f196eb062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;privacy&quot;)</value>
      <webElementGuid>edb94174-7522-42be-b45d-fcff93e8ecfc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='privacy']</value>
      <webElementGuid>b60b25ba-05ad-44cf-8b67-5ac6fed0018e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='myform-p-1']/div/div[2]/div[3]/div/div/input</value>
      <webElementGuid>4b1a6e99-cf18-4171-adbe-005f23fb5939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div/div[2]/div[3]/div/div/input</value>
      <webElementGuid>5de9f15c-7309-4f6f-b383-314007050d9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'privacy' and @name = 'privacy']</value>
      <webElementGuid>bb5792f5-0871-4ab7-b41b-c970e761df01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
