<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Describe in few words the most imp_0f1197</name>
   <tag></tag>
   <elementGuidId>8c27808d-3a44-4d0b-b6be-4016b6a5ceb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CompanyDescription</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='CompanyDescription']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>c022eca1-4a08-49c1-bb77-76e548489cf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>07e73a02-4cec-4213-a09c-250e8d6597a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>row</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>5d789ca9-f459-49c2-9698-e7020193a288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CompanyDescription</value>
      <webElementGuid>6d01c535-c97b-4798-94d3-ceaa88ebd661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CompanyDescription</value>
      <webElementGuid>9574baf0-de71-4e18-b0fc-475a0b328f04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter a short company description (minimum 50 characters)</value>
      <webElementGuid>aac09402-33e3-4b38-9da8-395ca445dfc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CompanyDescription&quot;)</value>
      <webElementGuid>3dab0185-9cee-4170-8125-6f8eab5a6e80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='CompanyDescription']</value>
      <webElementGuid>2c8750e7-6d52-4b95-8c09-328997086694</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='myform-p-0']/div/div/div/div[5]/div/textarea</value>
      <webElementGuid>6d7b19af-f69c-42dc-a29c-6b3ea0e70565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>6940a0e3-30ac-43d9-85ea-4ca9dcc1ca51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'CompanyDescription' and @id = 'CompanyDescription' and @placeholder = 'Enter a short company description (minimum 50 characters)']</value>
      <webElementGuid>b5d515e5-b5f2-4024-9228-87b194de322a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
