<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_I am looking for a job_input_job</name>
   <tag></tag>
   <elementGuidId>9507f3ff-f9b7-40db-971b-363ab3ec131e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;input_job&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='input_job']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>611ea870-2cd3-45eb-891f-c35644fa4ed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-field</value>
      <webElementGuid>063cb36d-1529-44b8-956b-8d821117423b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input_job</value>
      <webElementGuid>f1346638-6ce2-4a3b-9ccc-f8b64e0dc719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Describe the job you're looking for. For example: I am looking for a job as cook/warehouse worker/designer.</value>
      <webElementGuid>e858b1c9-405c-4a8b-ae9d-23d32e794db9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;premium-jobseeker-form&quot;)/div[@class=&quot;form-group-global display--flex flex--wrap p-sides&quot;]/textarea[@class=&quot;input-field&quot;]</value>
      <webElementGuid>2cda2f63-b801-4e6e-996e-c134a1494e72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='input_job']</value>
      <webElementGuid>dfcb23b3-de71-49fa-bae9-840df3d037bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='premium-jobseeker-form']/div[3]/textarea</value>
      <webElementGuid>e1748cb0-0d6c-4929-92cf-ca38dabf34ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>02e2ba02-4e60-44b7-8b6c-95a7ab1e1ba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'input_job' and @placeholder = concat(&quot;Describe the job you&quot; , &quot;'&quot; , &quot;re looking for. For example: I am looking for a job as cook/warehouse worker/designer.&quot;)]</value>
      <webElementGuid>a80648bf-0b21-45ec-9233-065f36ac4126</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
