<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_stairs_rc-image-tile-44</name>
   <tag></tag>
   <elementGuidId>1e4d8f13-149b-4b34-a0ab-493341afb6ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ddcd3b7b-e9e8-47c8-995b-c9970a191f45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>8c2e7279-a434-409d-8ac9-ce32c888eb28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AAYGu2R8GAoxcOdgvLTbe8Nrb4--iA6t-vFqaEfppjqPs5j5XFPn5mroGOMM0u2q7ykTRAzGbpMpp7dvgL6KhAIhG4qlBHXG0F_f7nDAxZLfMgtE1zuYc501AsWkUatVlYRf8CyUpIOodoju0mZ286vf2RW4XTz76eVaZF_FACwdIlZBDZFXm29f1jkEazdP_ivpVOPK7L6a3z9PM8NuPC6xacSNwPhoqA&amp;k=6LfiRzcaAAAAAF18-SQqrsovqK5dd4V8T1rgfpyC</value>
      <webElementGuid>976fdafd-642a-41c6-9f7b-f623033c856b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>77c3e22f-280a-464f-9681-9bac6fa4990e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/ContactJobSeeker/Page_Login to Jobstoday.world - Create Resu_ef8a51/iframe_Confirm My Choices_c-uuth7x30ma5z</value>
      <webElementGuid>44eb4a0f-8d7b-41c7-af63-7d08135a5038</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[2]/div/div/img</value>
      <webElementGuid>f38d5db6-84d4-45fa-ac94-92947ef8abd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AAYGu2R8GAoxcOdgvLTbe8Nrb4--iA6t-vFqaEfppjqPs5j5XFPn5mroGOMM0u2q7ykTRAzGbpMpp7dvgL6KhAIhG4qlBHXG0F_f7nDAxZLfMgtE1zuYc501AsWkUatVlYRf8CyUpIOodoju0mZ286vf2RW4XTz76eVaZF_FACwdIlZBDZFXm29f1jkEazdP_ivpVOPK7L6a3z9PM8NuPC6xacSNwPhoqA&amp;k=6LfiRzcaAAAAAF18-SQqrsovqK5dd4V8T1rgfpyC')])[10]</value>
      <webElementGuid>144fa43e-aa00-45ee-8a64-752156902aed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/div/div/img</value>
      <webElementGuid>2d1344ad-d3b1-49fc-9b24-a55f6efa5f70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AAYGu2R8GAoxcOdgvLTbe8Nrb4--iA6t-vFqaEfppjqPs5j5XFPn5mroGOMM0u2q7ykTRAzGbpMpp7dvgL6KhAIhG4qlBHXG0F_f7nDAxZLfMgtE1zuYc501AsWkUatVlYRf8CyUpIOodoju0mZ286vf2RW4XTz76eVaZF_FACwdIlZBDZFXm29f1jkEazdP_ivpVOPK7L6a3z9PM8NuPC6xacSNwPhoqA&amp;k=6LfiRzcaAAAAAF18-SQqrsovqK5dd4V8T1rgfpyC']</value>
      <webElementGuid>431d8384-68ec-47d5-a580-ab0e5e808231</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
