<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>2001</name>
   <tag></tag>
   <elementGuidId>33cef121-0c4a-4d9d-8ab2-0340dd430382</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;profile_info&quot;]/div[1]/div[1]/section/div/div[2]/div[2]/label/div[2]/div[1]/div[2]/ul/li[25]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
