<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Testing</name>
   <tag></tag>
   <elementGuidId>a0e26afe-f2ba-4a1d-bcda-eea9d7b877a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;page_content&quot;]/section/div/div/div/div[2]/div/div/ul</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#resume_3475 > div.b-resumes-list__info > div.b-resumes-list__info-item.b-resumes-list__info-item_text > div.b-resumes-list__text-info > div.b-resumes-list__item-position > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6f099799-0820-4517-bc85-9b8dfb993d18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en/my-resume/editResume/3475</value>
      <webElementGuid>5d0026d5-f3b1-45e9-8815-56c98d2547ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Testing</value>
      <webElementGuid>eb9396ad-2fce-4845-b7ca-bc0622f8a519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;resume_3475&quot;)/div[@class=&quot;b-resumes-list__info&quot;]/div[@class=&quot;b-resumes-list__info-item b-resumes-list__info-item_text&quot;]/div[@class=&quot;b-resumes-list__text-info&quot;]/div[@class=&quot;b-resumes-list__item-position&quot;]/a[1]</value>
      <webElementGuid>4abb2eb5-01b8-408c-b7f8-6f1004c2bebf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='resume_3475']/div/div[2]/div/div/a</value>
      <webElementGuid>46aa3dc0-deb7-4754-bd7f-d1c61b557296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Testing')]</value>
      <webElementGuid>d948c8e5-b3ea-4f67-a649-61ed8a444293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View resume'])[3]/following::a[1]</value>
      <webElementGuid>983a61f8-414b-4871-8781-55c22c975849</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mr.. Ahmed Ashraf, 22 years'])[3]/following::a[3]</value>
      <webElementGuid>2450af16-3819-4d25-91fe-357afa25b058</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mr.. Ahmed Ashraf, 22 years'])[4]/preceding::a[1]</value>
      <webElementGuid>59b03c7e-e8b3-4610-86b2-7deb4270e115</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View resume'])[4]/preceding::a[2]</value>
      <webElementGuid>d102fb38-066d-4fd6-b195-9f3565152eb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Testing']/parent::*</value>
      <webElementGuid>040a7d61-ee68-4bc1-8077-2ba6de6f2f8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/en/my-resume/editResume/3475')]</value>
      <webElementGuid>c9c09e9f-df20-4978-8757-34b1767e696e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/div[2]/div/div/a</value>
      <webElementGuid>a0154281-7818-4c78-af0d-f00ccd6c03e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/en/my-resume/editResume/3475' and (text() = 'Testing' or . = 'Testing')]</value>
      <webElementGuid>2916f74f-3493-49a4-8d3e-ce976f0d682c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
