<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save</name>
   <tag></tag>
   <elementGuidId>a9eecf5f-2259-4e5b-bb42-fd0dcac2cad9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.-ol-btn_sm.-ol-btn-success</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2083bebf-d603-4d73-bb2b-38f551907f56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>c2488c77-b8a4-47a3-aeae-08ee3324c185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>-ol-btn_sm -ol-btn-success</value>
      <webElementGuid>49c8133b-00d8-4a28-8c7f-a97d028be016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                        Save                                                                    </value>
      <webElementGuid>bb01879d-dcf5-4ce7-9377-b236b1ca6756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile_info&quot;)/div[@class=&quot;b-footer-control b-footer-control_last&quot;]/div[@class=&quot;b-footer-control__side b-footer-control__side_first&quot;]/div[@class=&quot;b-footer-control__side-inner&quot;]/div[@class=&quot;b-footer-control__side-inner-item&quot;]/button[@class=&quot;-ol-btn_sm -ol-btn-success&quot;]</value>
      <webElementGuid>152bd101-c9da-47f8-8bc2-15e9c8a53eab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>526c1e2c-a3c2-449f-ad6f-2bf341a4e10f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='profile_info']/div[2]/div/div/div/button</value>
      <webElementGuid>76f50666-47f2-4659-be47-a1e3e9bbf3b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Specify links to your social media profiles or personal website'])[1]/following::button[1]</value>
      <webElementGuid>efee7ae0-1735-4346-b0cd-c24e7079e736</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::button[1]</value>
      <webElementGuid>038b29b3-f8bd-4037-9fd7-3e5a64c677cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADDITIONAL INFORMATION'])[1]/preceding::button[2]</value>
      <webElementGuid>f8417261-61f6-4aa6-8023-6e839fd6ceb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>70c27915-98be-473e-b9f5-3fffdab44859</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div/div/button</value>
      <webElementGuid>800471dc-c0bc-47ed-b577-f081f6837391</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = '
                                                                        Save                                                                    ' or . = '
                                                                        Save                                                                    ')]</value>
      <webElementGuid>ee08431d-8d96-4a25-83ed-1123c39e9a43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
