<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select month of birth_jq-selectbox__tri_31cf56</name>
   <tag></tag>
   <elementGuidId>6a4f2fc0-eb96-4691-bba5-c962e35e7516</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;profile_info&quot;]/div[1]/div[1]/section/div/div[2]/div[1]/label/div[2]/div[1]/div[1]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8b444bc0-71de-40d7-8d81-099673deb8c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jq-selectbox__trigger-arrow</value>
      <webElementGuid>b80bc733-48c0-4a70-9679-d6066b25b2af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile_info&quot;)/div[@class=&quot;e-form-body&quot;]/div[@class=&quot;e-additional-info&quot;]/section[@class=&quot;e-text-info item&quot;]/div[@class=&quot;e-form-body&quot;]/div[@class=&quot;row-input&quot;]/div[@class=&quot;input-item&quot;]/label[@class=&quot;label-wrap&quot;]/div[@class=&quot;input-wrap&quot;]/div[@class=&quot;jq-selectbox jqselect e-input c-select&quot;]/div[@class=&quot;jq-selectbox__select&quot;]/div[@class=&quot;jq-selectbox__trigger&quot;]/div[@class=&quot;jq-selectbox__trigger-arrow&quot;]</value>
      <webElementGuid>ae2cf5f5-a96c-45d2-9bf9-7c49d58e9730</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='profile_info']/div/div/section/div/div[2]/div/label/div[2]/div/div/div[2]/div</value>
      <webElementGuid>4738dae4-b6e1-4ab9-a805-bc2a582ed9e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/label/div[2]/div/div/div[2]/div</value>
      <webElementGuid>84f37f1d-d556-4285-bdd0-793a8eb3d52b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
