<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>january</name>
   <tag></tag>
   <elementGuidId>53cc3ccb-19ed-45ef-90e5-48e6b2b493b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;profile_info&quot;]/div[1]/div[1]/section/div/div[2]/div[1]/label/div[2]/div[1]/div[2]/ul/li[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
