<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Confirm My Choices_c-798g2khiwcpd</name>
   <tag></tag>
   <elementGuidId>3688ca67-8c6c-4e50-b7fa-c84c1e27678e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='c-798g2khiwcpd']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;c-798g2khiwcpd&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>49b0290e-51b6-4b5f-9832-da36e96395b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>recaptcha challenge expires in two minutes</value>
      <webElementGuid>7afc73e0-9c10-4701-be35-ddb015a424b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>c-798g2khiwcpd</value>
      <webElementGuid>1c1ae890-c52f-416d-a547-82ba94d59002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a4c07159-50d1-4c7b-9e27-1fb30982185c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>58f475c2-be0c-421b-9ffd-b7a0794b8789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox</value>
      <webElementGuid>a661f7b3-770f-4cab-b907-22a348fb9e5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/bframe?hl=en&amp;v=fGZmEzpfeSeqDJiApS_XZ4Y2&amp;k=6LfiRzcaAAAAAF18-SQqrsovqK5dd4V8T1rgfpyC</value>
      <webElementGuid>58336b78-295b-47bb-a41a-430bb4c76c78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;candidate-login&quot;]/div[9]/div[4]/iframe[1]</value>
      <webElementGuid>539910eb-53ab-4f97-b20a-b7983747119b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='c-798g2khiwcpd']</value>
      <webElementGuid>72bde887-7ddb-4941-bb01-1e271c780aab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/iframe</value>
      <webElementGuid>b906ceb1-90fa-40ec-bc32-d5264239ecc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'recaptcha challenge expires in two minutes' and @name = 'c-798g2khiwcpd' and @src = 'https://www.google.com/recaptcha/api2/bframe?hl=en&amp;v=fGZmEzpfeSeqDJiApS_XZ4Y2&amp;k=6LfiRzcaAAAAAF18-SQqrsovqK5dd4V8T1rgfpyC']</value>
      <webElementGuid>85226d02-b745-44ca-ba5f-c7e6ad798f98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
