<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_stairs_rc-image-tile-33</name>
   <tag></tag>
   <elementGuidId>dcd8b6da-899e-4e3b-9719-bfdd3ae21286</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[2]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1e0fe54f-64ea-4c2d-9b12-de015e1b7aa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>eca8328e-f080-450a-8a66-871d858c2945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5FAnGJsEfS1j_SyG02ieNff8kGMNruIzJwZfOS_FgvAUSah6MW8LWKiZF7mi3oZfQQnt901wVTt9NIwLGSSxb4qoFnrj6ILEsvnpbbrcFLWiz-UNCLCqsDJPWK7_vP2s88T0ZylDVFb2YQcjnPIe3zhmaoy1iye-WzmK_8J3hQi5RI6aJnH5u1-C0lt0TzGXPTfPmJ&amp;k=6LfiRzcaAAAAAF18-SQqrsovqK5dd4V8T1rgfpyC</value>
      <webElementGuid>c844bf12-30ea-47ba-a08c-bfdadb890b21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>19c41459-e08d-4bed-891f-c4315016a465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/PostURLMonthlyJob/Page_Login to Jobstoday.world - Create Resu_ef8a51/iframe_Confirm My Choices_c-798g2khiwcpd</value>
      <webElementGuid>534265df-1b5e-4e01-b6a2-cb6e3609aa47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[2]/div/div/img</value>
      <webElementGuid>0a8329dc-8bcf-4df7-b480-c77d7da06170</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5FAnGJsEfS1j_SyG02ieNff8kGMNruIzJwZfOS_FgvAUSah6MW8LWKiZF7mi3oZfQQnt901wVTt9NIwLGSSxb4qoFnrj6ILEsvnpbbrcFLWiz-UNCLCqsDJPWK7_vP2s88T0ZylDVFb2YQcjnPIe3zhmaoy1iye-WzmK_8J3hQi5RI6aJnH5u1-C0lt0TzGXPTfPmJ&amp;k=6LfiRzcaAAAAAF18-SQqrsovqK5dd4V8T1rgfpyC')])[2]</value>
      <webElementGuid>bf4db3fc-3dbd-43f6-adcc-7055b57f5687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/img</value>
      <webElementGuid>e60ab5a4-eda2-4c1f-84b7-eba9bb08d40a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5FAnGJsEfS1j_SyG02ieNff8kGMNruIzJwZfOS_FgvAUSah6MW8LWKiZF7mi3oZfQQnt901wVTt9NIwLGSSxb4qoFnrj6ILEsvnpbbrcFLWiz-UNCLCqsDJPWK7_vP2s88T0ZylDVFb2YQcjnPIe3zhmaoy1iye-WzmK_8J3hQi5RI6aJnH5u1-C0lt0TzGXPTfPmJ&amp;k=6LfiRzcaAAAAAF18-SQqrsovqK5dd4V8T1rgfpyC']</value>
      <webElementGuid>3b7a8529-15a3-42c9-81ec-02e3d9263434</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
