<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3_4</name>
   <tag></tag>
   <elementGuidId>03c90126-8bbc-4e51-ab2e-4eefba4e84b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[3]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b0cf52d6-e0c9-4c62-a085-87a3ad960732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>b09b26df-9713-439d-ae4f-3d597ba04deb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7_FeM_oc1VF8YadSyIlF-Q033iCEkYJc3lacyD7U58zlDL-XA1XtDhyNd1UVfs175SuIQd-0HldhQz3O_-wGVlvo-g2ZX0Kvi7EwNkr_CAH35XHHMBzLQq0CD3RPuIiyH-zdyE_MsGCN3iIiC9ZGujpVWwNMpaHGGiSX37SWKtQMvgSx1o1X25ZuWVBPIH0GDIj0eDRwlQGoLb5iQvipNuxC9vbQ&amp;k=6LfiRzcaAAAAAF18-SQqrsovqK5dd4V8T1rgfpyC</value>
      <webElementGuid>19eb3720-659a-43b3-bd14-c251601b70f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>aa3531bd-ba53-4002-b224-96a06bcc98e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/SearchForJobUsingKeywordAndLocation/Page_Login to Jobstoday.world - Create Resu_ef8a51/iframe_Confirm My Choices_c-gcdc5819wtl3</value>
      <webElementGuid>3e9eca92-5acb-44c1-8993-ecd4ddb00095</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[3]/div/div/img</value>
      <webElementGuid>cfc043b1-708d-473e-9ca0-beccfc270355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7_FeM_oc1VF8YadSyIlF-Q033iCEkYJc3lacyD7U58zlDL-XA1XtDhyNd1UVfs175SuIQd-0HldhQz3O_-wGVlvo-g2ZX0Kvi7EwNkr_CAH35XHHMBzLQq0CD3RPuIiyH-zdyE_MsGCN3iIiC9ZGujpVWwNMpaHGGiSX37SWKtQMvgSx1o1X25ZuWVBPIH0GDIj0eDRwlQGoLb5iQvipNuxC9vbQ&amp;k=6LfiRzcaAAAAAF18-SQqrsovqK5dd4V8T1rgfpyC')])[7]</value>
      <webElementGuid>a2b1705c-d4c4-4818-9fe8-c0881adbb872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/div/div/img</value>
      <webElementGuid>aafb3328-2b04-4a6b-a5df-f80cd9bb0f8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7_FeM_oc1VF8YadSyIlF-Q033iCEkYJc3lacyD7U58zlDL-XA1XtDhyNd1UVfs175SuIQd-0HldhQz3O_-wGVlvo-g2ZX0Kvi7EwNkr_CAH35XHHMBzLQq0CD3RPuIiyH-zdyE_MsGCN3iIiC9ZGujpVWwNMpaHGGiSX37SWKtQMvgSx1o1X25ZuWVBPIH0GDIj0eDRwlQGoLb5iQvipNuxC9vbQ&amp;k=6LfiRzcaAAAAAF18-SQqrsovqK5dd4V8T1rgfpyC']</value>
      <webElementGuid>e024d1e4-aa5f-43d7-a9b1-2f9e95eb1517</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
