<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3</name>
   <tag></tag>
   <elementGuidId>9f104027-8b0a-48e0-93b6-5532dec399c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>02139a9a-b42c-49c5-90f0-e05c8b2566f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>977113a3-1220-40da-8e79-e154f88c168e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7qcznxvc0n0Di6yrRnaMAxWI18Z8q1lkNYp8kCqdhpOMUeQ1lfvUv5_-R3dfhNnmaa9yOrX0zYI6g1OuyiYLwlFAoIVR7PV30pZC7l0zsbi6uNYbZTS5jeUXlkTiaTzCGVV08IdjtPwEHcsNzzu23bMglSKXFXaNPdsks2Mg1rxTwj9xDivb2GlcKDoKFI8ZZdwPdr-QQm49MLpeI2cT_UC8hXDQ&amp;k=6LfiRzcaAAAAAF18-SQqrsovqK5dd4V8T1rgfpyC&amp;id=2</value>
      <webElementGuid>6357eb9a-79c8-45b7-a6ea-d5a3a88cc10d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>f03ef9c6-a1bf-4503-b6f5-d0c66f92ea3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/SearchForJobUsingKeywordAndLocation/Page_Login to Jobstoday.world - Create Resu_ef8a51/iframe_Confirm My Choices_c-gcdc5819wtl3</value>
      <webElementGuid>b8975460-6529-495f-b7f4-842b5b380b2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      <webElementGuid>456fb48a-9f96-4c14-bc2f-d8cd773607d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7qcznxvc0n0Di6yrRnaMAxWI18Z8q1lkNYp8kCqdhpOMUeQ1lfvUv5_-R3dfhNnmaa9yOrX0zYI6g1OuyiYLwlFAoIVR7PV30pZC7l0zsbi6uNYbZTS5jeUXlkTiaTzCGVV08IdjtPwEHcsNzzu23bMglSKXFXaNPdsks2Mg1rxTwj9xDivb2GlcKDoKFI8ZZdwPdr-QQm49MLpeI2cT_UC8hXDQ&amp;k=6LfiRzcaAAAAAF18-SQqrsovqK5dd4V8T1rgfpyC&amp;id=2')])[6]</value>
      <webElementGuid>d0561dc8-7975-4700-9966-9fc46516a590</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/div/img</value>
      <webElementGuid>654147dc-3f4a-465b-b572-c680abb1dd88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7qcznxvc0n0Di6yrRnaMAxWI18Z8q1lkNYp8kCqdhpOMUeQ1lfvUv5_-R3dfhNnmaa9yOrX0zYI6g1OuyiYLwlFAoIVR7PV30pZC7l0zsbi6uNYbZTS5jeUXlkTiaTzCGVV08IdjtPwEHcsNzzu23bMglSKXFXaNPdsks2Mg1rxTwj9xDivb2GlcKDoKFI8ZZdwPdr-QQm49MLpeI2cT_UC8hXDQ&amp;k=6LfiRzcaAAAAAF18-SQqrsovqK5dd4V8T1rgfpyC&amp;id=2']</value>
      <webElementGuid>ddabc02e-4fc2-4efb-955d-c94506efd085</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
