<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2</name>
   <tag></tag>
   <elementGuidId>1f825aff-efdb-4fc2-94b8-d8e00514c064</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e3bbb15a-0f8e-457d-aa25-405e2da9f269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>331cc2e0-079f-4c5c-b45f-d1be5ff948d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7qcznxvc0n0Di6yrRnaMAxWI18Z8q1lkNYp8kCqdhpOMUeQ1lfvUv5_-R3dfhNnmaa9yOrX0zYI6g1OuyiYLwlFAoIVR7PV30pZC7l0zsbi6uNYbZTS5jeUXlkTiaTzCGVV08IdjtPwEHcsNzzu23bMglSKXFXaNPdsks2Mg1rxTwj9xDivb2GlcKDoKFI8ZZdwPdr-QQm49MLpeI2cT_UC8hXDQ&amp;k=6LfiRzcaAAAAAF18-SQqrsovqK5dd4V8T1rgfpyC</value>
      <webElementGuid>98646451-f2cc-4046-b65f-e7e8f7c9d6c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>e08e1dd1-4940-4fad-8c75-3adf6ee60824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/SearchForJobUsingKeywordAndLocation/Page_Login to Jobstoday.world - Create Resu_ef8a51/iframe_Confirm My Choices_c-gcdc5819wtl3</value>
      <webElementGuid>033ba88b-0f4e-4977-80cd-9e16899d2814</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      <webElementGuid>5d23012d-dcc4-4d7e-95de-3d25d0789007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7qcznxvc0n0Di6yrRnaMAxWI18Z8q1lkNYp8kCqdhpOMUeQ1lfvUv5_-R3dfhNnmaa9yOrX0zYI6g1OuyiYLwlFAoIVR7PV30pZC7l0zsbi6uNYbZTS5jeUXlkTiaTzCGVV08IdjtPwEHcsNzzu23bMglSKXFXaNPdsks2Mg1rxTwj9xDivb2GlcKDoKFI8ZZdwPdr-QQm49MLpeI2cT_UC8hXDQ&amp;k=6LfiRzcaAAAAAF18-SQqrsovqK5dd4V8T1rgfpyC')])[6]</value>
      <webElementGuid>3ba24566-6064-4ee8-b289-a23fb058d471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/div/img</value>
      <webElementGuid>d14d6d49-7119-40a9-8c06-26c296871e42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7qcznxvc0n0Di6yrRnaMAxWI18Z8q1lkNYp8kCqdhpOMUeQ1lfvUv5_-R3dfhNnmaa9yOrX0zYI6g1OuyiYLwlFAoIVR7PV30pZC7l0zsbi6uNYbZTS5jeUXlkTiaTzCGVV08IdjtPwEHcsNzzu23bMglSKXFXaNPdsks2Mg1rxTwj9xDivb2GlcKDoKFI8ZZdwPdr-QQm49MLpeI2cT_UC8hXDQ&amp;k=6LfiRzcaAAAAAF18-SQqrsovqK5dd4V8T1rgfpyC']</value>
      <webElementGuid>78c4fac3-6d06-4f64-976a-5436da9fc559</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
