<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3_4_5</name>
   <tag></tag>
   <elementGuidId>69f648b0-fec6-4ba2-8c17-e99c1de4af19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[3]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0e1f99a3-a0e9-4620-bba5-eadb5d13c74d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>b884c7c9-ce4a-4a10-8e97-52a6a8ea5586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7_FeM_oc1VF8YadSyIlF-Q033iCEkYJc3lacyD7U58zlDL-XA1XtDhyNd1UVfs175SuIQd-0HldhQz3O_-wGVlvo-g2ZX0Kvi7EwNkr_CAH35XHHMBzLQq0CD3RPuIiyH-zdyE_MsGCN3iIiC9ZGujpVWwNMpaHGGiSX37SWKtQMvgSx1o1X25ZuWVBPIH0GDIj0eDRwlQGoLb5iQvipNuxC9vbQ&amp;k=6LfiRzcaAAAAAF18-SQqrsovqK5dd4V8T1rgfpyC&amp;id=2</value>
      <webElementGuid>cb22399a-bd28-4332-ae23-8126a05607e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>b46683fa-63fc-43b3-a42b-c50c2615cfe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/SearchForJobUsingKeywordAndLocation/Page_Login to Jobstoday.world - Create Resu_ef8a51/iframe_Confirm My Choices_c-gcdc5819wtl3</value>
      <webElementGuid>652b0c3e-80b9-437b-9d3f-68565cb7f589</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[3]/div/div/img</value>
      <webElementGuid>56a985b8-7789-4a53-868e-f843ac67e8f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7_FeM_oc1VF8YadSyIlF-Q033iCEkYJc3lacyD7U58zlDL-XA1XtDhyNd1UVfs175SuIQd-0HldhQz3O_-wGVlvo-g2ZX0Kvi7EwNkr_CAH35XHHMBzLQq0CD3RPuIiyH-zdyE_MsGCN3iIiC9ZGujpVWwNMpaHGGiSX37SWKtQMvgSx1o1X25ZuWVBPIH0GDIj0eDRwlQGoLb5iQvipNuxC9vbQ&amp;k=6LfiRzcaAAAAAF18-SQqrsovqK5dd4V8T1rgfpyC&amp;id=2')])[7]</value>
      <webElementGuid>bbb7605e-26c3-42f4-a5da-0d957dd24553</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/div/div/img</value>
      <webElementGuid>a44ee35e-a369-4315-8bb7-fffccc03a72e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7_FeM_oc1VF8YadSyIlF-Q033iCEkYJc3lacyD7U58zlDL-XA1XtDhyNd1UVfs175SuIQd-0HldhQz3O_-wGVlvo-g2ZX0Kvi7EwNkr_CAH35XHHMBzLQq0CD3RPuIiyH-zdyE_MsGCN3iIiC9ZGujpVWwNMpaHGGiSX37SWKtQMvgSx1o1X25ZuWVBPIH0GDIj0eDRwlQGoLb5iQvipNuxC9vbQ&amp;k=6LfiRzcaAAAAAF18-SQqrsovqK5dd4V8T1rgfpyC&amp;id=2']</value>
      <webElementGuid>d82766e4-2be6-4bd1-8d50-3db55f502d90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
