<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>emailForForget</name>
   <tag></tag>
   <elementGuidId>efad82cb-0541-4b40-8e3a-5548e74246fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[name='email']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
