<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>resetPasswordButton</name>
   <tag></tag>
   <elementGuidId>ff237dbe-2623-470e-887a-ecc9c2808aca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[type='submit']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>[type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
