<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bachelors</name>
   <tag></tag>
   <elementGuidId>8743084e-a00d-41b1-b948-0978e48a9d48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;education_form_add&quot;]/div[1]/div[2]/div[2]/label/div[2]/div[1]/div[2]/ul/li[4]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
