<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Poland</name>
   <tag></tag>
   <elementGuidId>b0804084-0b53-4c5a-92cf-ff7e04b99e0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;additional-info-nationality&quot;]/div[3]/div[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ms-res-item.ms-res-item-active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a5e92458-3fe5-41ad-8d3b-554f92a6cfc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-res-item ms-res-item-active</value>
      <webElementGuid>d4815f86-2544-401a-8240-2923a13da834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-json</name>
      <type>Main</type>
      <value>{&quot;id&quot;:176,&quot;name&quot;:&quot;Poland&quot;}</value>
      <webElementGuid>394c0ae3-4af6-45eb-93d5-0f58792fb284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Poland</value>
      <webElementGuid>de924837-a763-45f0-8d35-65ae3bb350ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;additional-info-nationality&quot;)/div[@class=&quot;ms-res-ctn dropdown-menu&quot;]/div[@class=&quot;ms-res-item ms-res-item-active&quot;]</value>
      <webElementGuid>cd270382-fcdd-4958-bbbf-eb649b3a14d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='additional-info-nationality']/div[3]/div[4]</value>
      <webElementGuid>3b35b149-84f1-493f-ab10-b73e8526b44e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Austria'])[1]/following::div[1]</value>
      <webElementGuid>ebc39934-2d2a-4bcc-9eb1-82bce60a635f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Germany'])[1]/following::div[2]</value>
      <webElementGuid>10c90df3-2a69-4fd0-aa62-37cd82a51b34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Afghanistan'])[1]/preceding::div[1]</value>
      <webElementGuid>ec0bb2a4-0e6a-4e26-9a35-b4406d637929</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aland Islands'])[1]/preceding::div[2]</value>
      <webElementGuid>b497cc18-e74a-4494-9b2e-20929281cb11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Poland']/parent::*</value>
      <webElementGuid>c1280510-8bb2-45bb-bc5f-280e8732f67a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div[4]</value>
      <webElementGuid>59364700-b88d-460d-96e4-f0a155781339</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Poland' or . = 'Poland')]</value>
      <webElementGuid>afe0bd5b-0f72-4581-82ca-fd8d49712069</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
