<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Contract</name>
   <tag></tag>
   <elementGuidId>1a0b6d81-f1ed-49e0-803e-20370e68dccd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;set-preferences-employment-type&quot;]/div[3]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ms-res-item.ms-res-item-active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ac134c5d-b779-4fab-90cd-849c649e72cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-res-item ms-res-item-active</value>
      <webElementGuid>20be99d9-0b98-4a5c-8771-e33aa54b4c9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-json</name>
      <type>Main</type>
      <value>{&quot;id&quot;:&quot;Contract&quot;,&quot;name&quot;:&quot;Contract&quot;}</value>
      <webElementGuid>ac635fdb-8c22-42ec-8fe6-9683f57d5914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Contract</value>
      <webElementGuid>5f1388c8-930f-4833-858e-1d6ae615b841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;set-preferences-employment-type&quot;)/div[@class=&quot;ms-res-ctn dropdown-menu&quot;]/div[@class=&quot;ms-res-item ms-res-item-active&quot;]</value>
      <webElementGuid>4d729c2c-c633-4302-bdd2-ac2aa0642ae7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='set-preferences-employment-type']/div[3]/div[2]</value>
      <webElementGuid>7f9dca27-3121-4ccc-a000-63e605b9cd53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permanent'])[1]/following::div[1]</value>
      <webElementGuid>21233ac0-2dfd-4404-9772-dae06073758e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Specify your ideal employment type. You can specify up to 3 different employment types.'])[1]/following::div[10]</value>
      <webElementGuid>96200fef-c7aa-4960-b26a-ef2b29bc8198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Temporary'])[1]/preceding::div[1]</value>
      <webElementGuid>141f160a-bcdc-4376-9daa-6ad080ddf157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project'])[1]/preceding::div[2]</value>
      <webElementGuid>4b87badb-7374-4c01-b5fd-80fc1a43ffd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Contract']/parent::*</value>
      <webElementGuid>5ab0ae08-8fa0-4011-837d-de6dca9bfaaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[3]/div[2]</value>
      <webElementGuid>6c43dd18-f9b2-4069-9359-2d265e21b765</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Contract' or . = 'Contract')]</value>
      <webElementGuid>5699d8a1-f630-490f-9147-6fbcbfce37c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
