<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>eduarrow</name>
   <tag></tag>
   <elementGuidId>9a2e1ed6-cb8a-471a-b0c0-8f54fdffd4cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;education_form_add&quot;]/div[1]/div[2]/div[2]/label/div[2]/div[1]/div[1]/div[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
