<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_text_1_2</name>
   <tag></tag>
   <elementGuidId>a84a55ef-3244-4d39-a353-ca81cb0e27b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[19]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#set-preferences-skills-keywords > div.ms-sel-ctn > input[type=&quot;text&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>55f73759-0ccd-47a0-8d1c-58eef64f87ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5167fa18-0959-4605-960c-7ffbba4ea396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Add Skills keywords</value>
      <webElementGuid>3e732c6f-0a50-4f1c-bb68-ec40ccccc359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;set-preferences-skills-keywords&quot;)/div[@class=&quot;ms-sel-ctn&quot;]/input[1]</value>
      <webElementGuid>fedbe51f-13a6-41d6-8f23-cdb8405d3699</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[19]</value>
      <webElementGuid>d6f76f1a-dd38-4706-aad6-642a1ae932ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='set-preferences-skills-keywords']/div/input</value>
      <webElementGuid>650ed715-ad29-496a-ab0a-1ef7adc80508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/label/div[2]/div/div/div/input</value>
      <webElementGuid>0db54029-ec05-4b34-a055-3d92df8e0aae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Add Skills keywords']</value>
      <webElementGuid>252b804b-d13e-4bfb-b00d-9b64d2f6df0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
