<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Select year_currently</name>
   <tag></tag>
   <elementGuidId>85aadff2-966c-46d8-bf57-687344c0e17f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='professional-experience-1-currently-work']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#professional-experience-1-currently-work</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2244a46a-b46d-4982-b9d9-6b713b3cb2fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>currently</value>
      <webElementGuid>21baa5de-de95-4b16-9bb7-bcb6dc0f990c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>updateTillDate_create_professional_expirience_form_3488()</value>
      <webElementGuid>d6a0a420-1379-448b-9138-5239dcb62728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e182d58e-3f92-497e-8ddd-d15fb219a2ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>professional-experience-1-currently-work</value>
      <webElementGuid>35166882-909d-4a74-8998-9df9e64da5d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>35f67dd0-5dc1-4e18-8ab8-9bad1fc751b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>-ol-checkbox__input</value>
      <webElementGuid>e402e37f-6a6a-49c1-ba09-ae22f8902dd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;professional-experience-1-currently-work&quot;)</value>
      <webElementGuid>b9e133f4-8768-489f-a221-9481fcbf57f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='professional-experience-1-currently-work']</value>
      <webElementGuid>0023a2e3-e0ab-4849-83c3-2c0d4df9eb6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='create_professional_expirience_form_3488']/div/div[5]/div/div/div/div/div/input</value>
      <webElementGuid>e7206621-a69d-43bf-817e-d2a8234b8f4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div/input</value>
      <webElementGuid>c410c78b-8f17-4714-a35d-42da36dec073</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'currently' and @id = 'professional-experience-1-currently-work' and @type = 'checkbox']</value>
      <webElementGuid>2e943bda-615f-4bbc-984c-1da1b175a3b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
