<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Administration</name>
   <tag></tag>
   <elementGuidId>85e31b8d-848e-4e72-9e22-ad777258606a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.jq-selectbox.jqselect.e-input.c-select.dropdown.opened > div.jq-selectbox__dropdown > ul > li:nth-of-type(4)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[contains(text(),'Accounting/Tax/Legal')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>238dea47-5d04-48dd-bb88-4a8a7215ff41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Administration</value>
      <webElementGuid>d8c413e2-e3d7-4b71-a966-be894b9c1288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;create_professional_expirience_form_3488&quot;)/div[@class=&quot;e-form-body&quot;]/div[@class=&quot;row-input&quot;]/div[@class=&quot;input-item&quot;]/label[@class=&quot;label-wrap&quot;]/div[@class=&quot;input-wrap error&quot;]/div[@class=&quot;jq-selectbox jqselect e-input c-select dropdown opened&quot;]/div[@class=&quot;jq-selectbox__dropdown&quot;]/ul[1]/li[4]</value>
      <webElementGuid>2bab5ea1-ac90-45ec-871c-27b66a535c9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='create_professional_expirience_form_3488']/div/div[2]/div/label/div[2]/div/div[2]/ul/li[4]</value>
      <webElementGuid>dd7656a1-d1ed-4822-b130-b21f4a86ea47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accounting/Tax/Legal'])[2]/following::li[1]</value>
      <webElementGuid>d357653c-e317-49c3-9747-4062d68d46f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accounting'])[2]/following::li[2]</value>
      <webElementGuid>3f304a33-3afc-4bd1-9b85-f9ad65913c23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advertising/Media'])[2]/preceding::li[1]</value>
      <webElementGuid>f2308546-13ef-480b-bf4a-fa18c9e074c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agencies/Sponsors'])[2]/preceding::li[2]</value>
      <webElementGuid>472209f9-8a33-4b6b-ac2f-ca16b0823cc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[7]/div[2]/div[2]/div/form/div/div[2]/div/label/div[2]/div/div[2]/ul/li[4]</value>
      <webElementGuid>b8bf9618-3838-4260-8642-389f752bbfd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Administration' or . = 'Administration')]</value>
      <webElementGuid>f26ec22d-ef70-4ba9-a34c-763196f1e943</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
