<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_HH-AT-2023-11-0010_privacy</name>
   <tag></tag>
   <elementGuidId>697b5ef9-5afb-4d12-8907-5b1270c08927</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='privacy']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#privacy</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>589cbc40-cafb-4857-ace5-a235558cf6e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e8a73c98-5c5b-4fda-80de-8b1181f3cd47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>privacy</value>
      <webElementGuid>a76503eb-cc4c-4081-abeb-10d122711c70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>privacy</value>
      <webElementGuid>7f3d249a-966e-4ae7-aeec-d9b36b64fbc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;privacy&quot;)</value>
      <webElementGuid>d8ab6683-3b2a-4d1f-baf5-45014d29ea31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='privacy']</value>
      <webElementGuid>9ea70eee-e409-421e-b6ca-59f772b9183a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='myform-p-1']/div/div[2]/div[3]/div/div/input</value>
      <webElementGuid>05ff84c7-854f-4be2-8e24-2544ba2d73ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div/div[2]/div[3]/div/div/input</value>
      <webElementGuid>39abcc06-04e2-419f-bc4f-5cbfac6a1dbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'privacy' and @name = 'privacy']</value>
      <webElementGuid>1324076e-4b01-4d2e-8026-f838111c1ae6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
