<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Enter a short Job description, it _305c38</name>
   <tag></tag>
   <elementGuidId>11f43476-0878-4653-957d-639d37a4b87e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='short_description']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#short_description</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>a10df232-20b5-4ed9-bc21-7369dba9e81a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>dc51ac81-a96a-484d-8ce9-3ea15d16a22b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>row</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>37cc26cf-822c-42e8-bbd1-fc1e1302d9f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>short_description</value>
      <webElementGuid>74449261-d855-4b33-b46c-b3485edec640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>short_description</value>
      <webElementGuid>fe5364e2-2d02-42ae-adb6-08385050230d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Job description (min 50 characters)</value>
      <webElementGuid>a2ff4095-a6aa-4d6e-8df6-67d16f01dbbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;short_description&quot;)</value>
      <webElementGuid>8da12abb-36c8-45c0-9f5c-7e3aed701977</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='short_description']</value>
      <webElementGuid>cbb39a83-89f0-4b3c-98e2-ace0bb1dce69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='myform-p-0']/div/div/div/div[7]/div/textarea</value>
      <webElementGuid>2a653c56-25ef-46f2-95ac-65488ba72f68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/textarea</value>
      <webElementGuid>4c78defb-9a8f-486a-afa1-a0d41eb0d5f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'short_description' and @id = 'short_description' and @placeholder = 'Enter Job description (min 50 characters)']</value>
      <webElementGuid>636d50ec-9f9c-455c-83ec-554bb208b050</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
