<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_HH-AT-2023-10-0004_privacy</name>
   <tag></tag>
   <elementGuidId>ca08ec8d-af48-4492-bc3f-eec4b1f466ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='privacy']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#privacy</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c803d493-4d20-49e0-aa81-d12a2fc15e15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>0cb32b6d-38dd-4085-b46b-28b97e0ab753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>privacy</value>
      <webElementGuid>bc512bf3-fd4f-4019-b198-96e78f5594ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>privacy</value>
      <webElementGuid>e0a46191-c50f-4a0c-a03f-0ff91660f283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;privacy&quot;)</value>
      <webElementGuid>3e0ff61d-ef5e-4295-a184-9f05c7b4c52e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='privacy']</value>
      <webElementGuid>2b937c2f-87bd-4b08-baa5-3227d9b9de4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='myform-p-1']/div/div[2]/div[3]/div/div/input</value>
      <webElementGuid>697d3de0-c2ff-4a7d-a66d-99c2050e38ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div/div[2]/div[3]/div/div/input</value>
      <webElementGuid>5f9cb338-aba1-428c-83ae-7f4e12d950fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'privacy' and @name = 'privacy']</value>
      <webElementGuid>80c7162e-9f7e-4304-830e-f045e38d26c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
