<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_No</name>
   <tag></tag>
   <elementGuidId>9c28d418-4e91-4d6c-829b-71f927313aeb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//fieldset[@id='myform-p-0']/div/div/div[2]/div[6]/div/label[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.add-position-information > div.form-group.company-contact-detail > div.custom-checkbox > label:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>ec131137-5e01-45fc-aaf6-fb8e80a610ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>radio_button-08</value>
      <webElementGuid>ee26e23b-cdcb-4aee-8cdd-1f7948ed33e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No</value>
      <webElementGuid>74d3b08c-cc44-4de9-8a04-22d656852de0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myform-p-0&quot;)/div[@class=&quot;form-tab&quot;]/div[@class=&quot;tab-content current&quot;]/div[@class=&quot;add-position-information&quot;]/div[@class=&quot;form-group company-contact-detail&quot;]/div[@class=&quot;custom-checkbox&quot;]/label[2]</value>
      <webElementGuid>c2ff534a-efc8-410b-a0b1-327f242b517f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='myform-p-0']/div/div/div[2]/div[6]/div/label[2]</value>
      <webElementGuid>f0ff0050-d9a5-49b7-bd13-4dc04c5a7a22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[3]/following::label[1]</value>
      <webElementGuid>1b716b0f-9e32-43d1-897f-2c02cb5c7574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select this option to ask the candidate for address, phone number, date of birth.'])[1]/following::label[2]</value>
      <webElementGuid>74d0aad4-2348-4979-8bca-d59155966171</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select application process'])[1]/preceding::label[1]</value>
      <webElementGuid>6d36d4de-95db-48af-a0aa-3d58d3f329c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/label[2]</value>
      <webElementGuid>dbde92ed-74de-4969-9fcd-c7f20256ab9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'No' or . = 'No')]</value>
      <webElementGuid>c2ff8a24-8ec4-4c47-bcc0-ac62f54cf0e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
