<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Text Job Posting</name>
   <tag></tag>
   <elementGuidId>6c9825cb-b6ea-4ad8-aa52-00efe65135d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//fieldset[@id='myform-p-0']/div/ul/li</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.tab-link.current</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>4b9753de-6830-4ca1-96ce-46d6b5272c83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tab-link current</value>
      <webElementGuid>6cc5e3f7-4848-4c44-b8a2-bdff83dc6c21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tab</name>
      <type>Main</type>
      <value>job-text</value>
      <webElementGuid>94bc967d-8cb4-4760-a4b7-4b61e0614f39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-jobtype</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6b325d3c-c9e8-46a8-a0c1-2d42d3d6f803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Text Job Posting                                                </value>
      <webElementGuid>34a49f98-bad5-48b7-bd18-c9def7a43d16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myform-p-0&quot;)/div[@class=&quot;form-tab&quot;]/ul[@class=&quot;tabs&quot;]/li[@class=&quot;tab-link current&quot;]</value>
      <webElementGuid>d937be17-cc58-473e-aa7f-b6787d5ac507</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='myform-p-0']/div/ul/li</value>
      <webElementGuid>af79d2b0-8222-4354-bc00-c32fcbb32aa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Step 1 of 2'])[1]/following::li[1]</value>
      <webElementGuid>6c70010c-a381-41b7-96f2-b516b0c7c764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='current step:'])[1]/following::li[3]</value>
      <webElementGuid>30d3ab39-d9ff-49a5-897e-925d80a26441</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='URL Job Posting'])[1]/preceding::li[1]</value>
      <webElementGuid>d27718bb-2902-4c70-8ad6-2997e24b3a9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add your Job details'])[1]/preceding::li[2]</value>
      <webElementGuid>520ce13b-e933-40d8-b27f-a14d2485ae8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Text Job Posting']/parent::*</value>
      <webElementGuid>a25e5fee-9639-4247-be6b-e5b14c01878e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/ul/li</value>
      <webElementGuid>d31c64f0-b777-443a-b7e5-69338356a8de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Text Job Posting                                                ' or . = 'Text Job Posting                                                ')]</value>
      <webElementGuid>4bbcfc40-a20c-45b8-9a64-4eed4113499b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
