<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select number</name>
   <tag></tag>
   <elementGuidId>306120e5-32e4-49fe-8402-e3e40891becb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-input_number_of_employee-cm-container']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-input_number_of_employee-cm-container > span.select2-selection__placeholder</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8304d33b-4a5c-4445-baea-6e15a83a8131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__placeholder</value>
      <webElementGuid>854ecc90-d374-482b-96ab-a239afa0c229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select number</value>
      <webElementGuid>4ff42ff3-abcf-452b-99b6-8f23c446c48b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-input_number_of_employee-cm-container&quot;)/span[@class=&quot;select2-selection__placeholder&quot;]</value>
      <webElementGuid>fe702074-5bb0-4d9f-b729-368c342479b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='select2-input_number_of_employee-cm-container']/span</value>
      <webElementGuid>a1b38429-4785-409b-a64d-ef17358564a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select communication language'])[2]/following::span[8]</value>
      <webElementGuid>8214866f-31ba-464e-a8d7-0ed1d4221657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registration Error'])[1]/preceding::span[4]</value>
      <webElementGuid>15252631-3bc4-4a75-9120-19e4a2e99193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose your payment method'])[1]/preceding::span[5]</value>
      <webElementGuid>e5ab6b38-9ad7-4d71-9e3d-d3167bf52e2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/span/span/span/span</value>
      <webElementGuid>03c94a4b-12c5-4f4b-9ff9-1a9c34398099</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Select number' or . = 'Select number')]</value>
      <webElementGuid>3f515ef3-6571-4fc0-8a82-2915631117f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
