<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select SalaryRate</name>
   <tag></tag>
   <elementGuidId>2fe39e23-06fc-49ad-b6ba-cfad97ff2a7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-select_salary-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-select_salary-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>32d2766b-31fa-4a9e-bc86-85b8ab9cf976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>0ad55cc4-20f7-45b0-9f7b-79d284d040ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-select_salary-container</value>
      <webElementGuid>177e2e11-c3a7-4be9-b133-d669795126f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>49fabb2f-b2ef-4bde-a5ea-d9b96895d2d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8b8ed3ee-7cb1-4252-881d-fb36af02188f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Salary/Rate</value>
      <webElementGuid>5334e500-39f3-4ce6-9c5f-00a284286cce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-select_salary-container&quot;)</value>
      <webElementGuid>2e53050e-4359-4844-b6a8-bebbcc94906b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-select_salary-container']</value>
      <webElementGuid>e338be27-2a06-4913-98f6-f7f7c0c2b6b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='myform-p-0']/div/div/div[2]/div[4]/div[2]/div/span/span/span/span</value>
      <webElementGuid>a53a840d-78fd-4455-b696-4dafd365cb09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Specify yearly salary or hourly/daily rate.'])[1]/following::span[4]</value>
      <webElementGuid>4c3e0e60-dc22-4458-9488-c4714ef21e3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/span/span/span/span</value>
      <webElementGuid>309b8971-0226-4ba9-bb13-5fc45f89514f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-select_salary-container' and (text() = 'Select Salary/Rate' or . = 'Select Salary/Rate')]</value>
      <webElementGuid>761d15b7-4aa5-4af9-8074-e02ee127354e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
