<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Describe in few words the most imp_0f1197</name>
   <tag></tag>
   <elementGuidId>f2842772-777c-4edf-abaa-4680eebc8288</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='CompanyDescription']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CompanyDescription</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>f438ff3d-b0c3-496b-aee1-51dccd3a235f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>07ff3432-2ca8-457f-9adf-732a72e4db25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>row</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>1c323de6-97cb-4ff9-ac95-47d497fb87cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CompanyDescription</value>
      <webElementGuid>8a982dd6-1b1c-4579-a97b-3c135358dc69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CompanyDescription</value>
      <webElementGuid>514d8519-88c2-4541-bd10-1d332dd65c58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter a short company description (minimum 50 characters)</value>
      <webElementGuid>b85eca10-1d9a-4c30-8772-a4afcb148e21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CompanyDescription&quot;)</value>
      <webElementGuid>a5e8bcaf-189c-4add-acf2-5bd123704532</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='CompanyDescription']</value>
      <webElementGuid>4ec8b537-51d8-42a5-85cb-f70910af46f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='myform-p-0']/div/div/div/div[5]/div/textarea</value>
      <webElementGuid>3db0ad17-6f7b-44ae-9890-f30c7adad20f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>3698d1bf-4ede-484b-8c1f-a89f8874f9be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'CompanyDescription' and @id = 'CompanyDescription' and @placeholder = 'Enter a short company description (minimum 50 characters)']</value>
      <webElementGuid>29c48a6c-659d-4d96-9be1-5bc92c745a2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
