<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>applyFilterButton</name>
   <tag></tag>
   <elementGuidId>fb72d154-677d-4c0b-8166-c0c7a2ead96f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a#applyfilters-findjobs</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='searchForm']/div[2]/div/div[2]/div[5]/button[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d4261ca0-b040-4430-84e0-b76985e13903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mobile-hidden</value>
      <webElementGuid>c64d9bf3-96ad-458c-800d-9784d8c91c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>9349783e-172a-4337-994e-cd0f0f50cc20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchForm&quot;)/div[@class=&quot;advance-search active--filter&quot;]/div[@class=&quot;advance-search-inner&quot;]/div[@class=&quot;search-advanced display--flex flex--wrap&quot;]/div[@class=&quot;apply-button display--flex align-item--center&quot;]/button[@class=&quot;apply_button&quot;]/span[@class=&quot;mobile-hidden&quot;]</value>
      <webElementGuid>69cfbc09-ab04-4abd-b5da-af84a0e54cad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchForm']/div[2]/div/div[2]/div[5]/button[2]/span</value>
      <webElementGuid>70dfc394-cb2f-430f-9a85-dfe0636bd65c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear'])[1]/following::span[1]</value>
      <webElementGuid>8b2af132-5fb1-4da4-9be2-007c5a9aa2bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Jobs'])[2]/following::span[3]</value>
      <webElementGuid>5135c2c3-3b50-43cd-8c11-5ce66c4d0ad0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply'])[1]/preceding::span[1]</value>
      <webElementGuid>8eaca51f-3f95-4538-8c68-b59bd58367dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort by'])[1]/preceding::span[2]</value>
      <webElementGuid>48c991b4-9879-435a-b1e7-8b9d18e29ebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span</value>
      <webElementGuid>ab8dfa3a-9fe6-42f0-b8c3-6494e92b1f42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Search' or . = 'Search')]</value>
      <webElementGuid>10665ab4-bd36-4ace-80cd-191b74288dcb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
