<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Germany</name>
   <tag></tag>
   <elementGuidId>86e7a455-2a9a-41da-9c5d-32ac424a5999</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-country-result-73er-55</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='select2-country-result-73er-55']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>c20f3bbb-ad54-4b59-93de-ae58b2e35ccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>af0c4544-0c0c-4724-bb4c-46b969da9bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-country-result-73er-55</value>
      <webElementGuid>82ca9bdf-8816-45aa-9e07-0c03ceb69eb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>treeitem</value>
      <webElementGuid>119f75e1-18f7-49a5-b8aa-6e352e0255ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e40ff9d1-8c67-42d5-a0a0-1985a1e98192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>select2-country-result-73er-55</value>
      <webElementGuid>c959fce0-4297-4c3a-adce-b2820d130719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Germany</value>
      <webElementGuid>36e7838a-21f6-47a9-a296-19c7567bd0d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-country-result-73er-55&quot;)</value>
      <webElementGuid>eec5a3c7-5896-4eb7-8cbf-61214bd87df4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-country-result-73er-55']</value>
      <webElementGuid>c82f9e31-1ba3-44b6-a65f-61e69d172e58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-country-results']/li[2]</value>
      <webElementGuid>dd809f4b-a5a6-4d31-b5f6-6c11a10c7e8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Switzerland'])[2]/following::li[1]</value>
      <webElementGuid>19bcab77-d7d9-425b-b5ad-fd19cc144d36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm My Choices'])[1]/following::li[2]</value>
      <webElementGuid>b119d07a-3a64-4957-833b-7c89330ed6f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Austria'])[2]/preceding::li[1]</value>
      <webElementGuid>1868e407-c7ef-417d-8a22-11fee236e66a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Poland'])[2]/preceding::li[2]</value>
      <webElementGuid>18866ac0-1658-4c35-ba09-9fdab18a536f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/span/span/span/ul/li[2]</value>
      <webElementGuid>908b76f2-e998-4da2-9b0a-9c27d3789f5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-country-result-73er-55' and (text() = 'Germany' or . = 'Germany')]</value>
      <webElementGuid>25174a30-9ff1-4097-980f-dfd40bd7c06e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
