<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>locationInputWhenSearching</name>
   <tag></tag>
   <elementGuidId>c92e9fda-7723-42cd-937e-ce48c34a8e52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input#location</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[contains(@class, 'type-and-location')] /span[contains(@class,'JobLocation')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>7bd539f4-738d-4b61-948f-e0d340ddb441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-result</value>
      <webElementGuid>c0092432-421a-490c-b0f1-f4bdd45198f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>4977362 jobs found</value>
      <webElementGuid>fca31bd7-1144-4d2f-bc73-d5cdcaff86a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;job-sort-order&quot;)/p[@class=&quot;search-result&quot;]</value>
      <webElementGuid>e23ca3c9-bc6e-4418-a378-f816cb452bcb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='job-sort-order']/p</value>
      <webElementGuid>d29a86fe-a140-4628-a036-00182a20cebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find a Job'])[1]/following::p[1]</value>
      <webElementGuid>be25b827-f10c-43ef-beef-c5b2661257b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply'])[2]/following::p[2]</value>
      <webElementGuid>e46c2713-34be-457d-b3fc-7e486d1d6130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find a Job'])[2]/preceding::p[1]</value>
      <webElementGuid>86e04878-834a-4994-b90e-9b702960b2b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Relevance'])[2]/preceding::p[1]</value>
      <webElementGuid>b053aec2-449c-466a-9b01-3b93135fff17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/p</value>
      <webElementGuid>fc167347-5d02-47ea-bfaf-8c25578e72a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '4977362 jobs found' or . = '4977362 jobs found')]</value>
      <webElementGuid>2f79e289-2f24-4677-996c-f223614fbb1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
