<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_4977362 jobs found</name>
   <tag></tag>
   <elementGuidId>c92e9fda-7723-42cd-937e-ce48c34a8e52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#job-sort-order > p.search-result</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='job-sort-order']/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>f76d3f56-1141-4547-ae18-a0e40ed41055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-result</value>
      <webElementGuid>455985e6-166f-4359-9548-edee5ffdc96a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>4977362 jobs found</value>
      <webElementGuid>262dfd8f-435a-469c-bf7f-32deeb2467fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;job-sort-order&quot;)/p[@class=&quot;search-result&quot;]</value>
      <webElementGuid>8a8a515b-92ff-44f6-bbf1-72f0084d86e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='job-sort-order']/p</value>
      <webElementGuid>84a4f0a0-5498-49b9-acbb-55936e3ff501</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find a Job'])[1]/following::p[1]</value>
      <webElementGuid>e805c6db-3036-4ae7-848c-2cd1236e72cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply'])[2]/following::p[2]</value>
      <webElementGuid>7e0f60fc-6bb5-4ee7-bf3f-95995f17983e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find a Job'])[2]/preceding::p[1]</value>
      <webElementGuid>63c55b10-1a95-4237-8b6c-b811cc047ab3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Relevance'])[2]/preceding::p[1]</value>
      <webElementGuid>a6eca4e9-b005-4db9-8246-234e8b721cce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/p</value>
      <webElementGuid>7cfff70d-b1bd-47bf-aafb-7751bff04979</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '4977362 jobs found' or . = '4977362 jobs found')]</value>
      <webElementGuid>36189b39-1735-4816-95fa-6bcb82496971</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
