<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Search</name>
   <tag></tag>
   <elementGuidId>fb72d154-677d-4c0b-8166-c0c7a2ead96f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.mobile-hidden</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='searchForm']/div[2]/div/div[2]/div[5]/button[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>69628be2-3727-4697-9103-b3e32739e1a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mobile-hidden</value>
      <webElementGuid>d0d32303-c593-4e1f-94c9-060851720eb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>f8c92125-18ab-46d2-b3aa-bb519c54eb00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchForm&quot;)/div[@class=&quot;advance-search active--filter&quot;]/div[@class=&quot;advance-search-inner&quot;]/div[@class=&quot;search-advanced display--flex flex--wrap&quot;]/div[@class=&quot;apply-button display--flex align-item--center&quot;]/button[@class=&quot;apply_button&quot;]/span[@class=&quot;mobile-hidden&quot;]</value>
      <webElementGuid>02b07565-5034-4404-9739-971fc812b152</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchForm']/div[2]/div/div[2]/div[5]/button[2]/span</value>
      <webElementGuid>79cf0219-3b96-4841-b78a-6cc663fc2c0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear'])[1]/following::span[1]</value>
      <webElementGuid>ecdb6c61-62b4-4fa1-9883-8e3054e1a311</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Jobs'])[2]/following::span[3]</value>
      <webElementGuid>8156d411-3757-4111-bc12-0f78c758c7fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply'])[1]/preceding::span[1]</value>
      <webElementGuid>1c140f7a-203a-4005-9d32-a30cd25708af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort by'])[1]/preceding::span[2]</value>
      <webElementGuid>b6a55d65-e856-4505-9476-8e809b31e1cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span</value>
      <webElementGuid>1511348c-b886-447d-8484-57c9e285c62f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Search' or . = 'Search')]</value>
      <webElementGuid>71172afa-9922-48b5-bbf7-74e7b6f39d02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
