<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>728492d9-1afa-4576-864b-81c1887f38e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.user-login > a > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/div[3]/div[2]/ul/li/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d7f9d333-d3b5-4a72-bf38-dc4c9baeeceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/images/icon/user.svg</value>
      <webElementGuid>54056cf3-2467-455f-a1d6-c185b0cae88c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;header-menu&quot;]/div[@class=&quot;vertical-menu right--menu mobile-hidden&quot;]/ul[@class=&quot;display--flex align-item--center&quot;]/li[@class=&quot;user-login&quot;]/a[1]/img[1]</value>
      <webElementGuid>ea321f1c-91eb-4cf7-a444-b9845977016b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/div[3]/div[2]/ul/li/a/img</value>
      <webElementGuid>7d0f7625-5a55-49f2-90df-4384ea3a4a97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/ul/li/a/img</value>
      <webElementGuid>c1b31572-2c49-46b5-840c-9edb828ebe58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/images/icon/user.svg']</value>
      <webElementGuid>33e8a7a7-1c30-42ce-826e-d3bc5b7dbc17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
