<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Company name_input_company</name>
   <tag></tag>
   <elementGuidId>9161dc23-5652-43ae-b666-497875bf55aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='input_company']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;input_company&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a7bc1845-5c44-4aa7-a5b9-c5325e596a41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputMaterial input-group</value>
      <webElementGuid>22fd0f79-ee4d-422e-a389-38fb5822e623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input_company</value>
      <webElementGuid>915d3291-4f23-46df-bdcd-0be62a1701b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a11fb3cf-5d5c-404f-bc5d-fc27e81f1b97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contact-form&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;form-group-inner&quot;]/input[@class=&quot;inputMaterial input-group&quot;]</value>
      <webElementGuid>0deaeff0-fdd0-4a48-bb51-080399f9508d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='input_company']</value>
      <webElementGuid>b445743f-d115-4cdf-9878-07931f6d47bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='contact-form']/div[2]/div/input</value>
      <webElementGuid>27714598-4d1e-4d1c-b2e9-903a8f963541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>9ffd033a-a49f-4858-adfc-cda39535992b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'input_company' and @type = 'text']</value>
      <webElementGuid>e2a8013c-4d35-4dc9-8a4b-d7e22b662f06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
