<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone number_input_phone</name>
   <tag></tag>
   <elementGuidId>79c2e7d3-0066-4cba-82ac-983b43079a88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='input_phone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;input_phone&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3f808e59-2f6c-409a-b522-238a7cd2eec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputMaterial input-group</value>
      <webElementGuid>3ecaa285-152f-4f11-ae47-a43c95158beb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input_phone</value>
      <webElementGuid>e0ce1f9a-c74f-4f33-a0b5-d448cdd5a3c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f5f84a43-409e-49ad-80af-ecfe6f67a0af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contact-form&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;form-group-inner group&quot;]/input[@class=&quot;inputMaterial input-group&quot;]</value>
      <webElementGuid>7332ae44-a12e-44e6-97f2-9647924824fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='input_phone']</value>
      <webElementGuid>65d4201d-5e0a-402d-847d-8720056ec059</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='contact-form']/div[2]/div[2]/input</value>
      <webElementGuid>7b645d9c-b87b-4084-9980-87412f640b1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>1e0ef308-3545-474c-a22a-649a07946aa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'input_phone' and @type = 'text']</value>
      <webElementGuid>26dbe0c7-6bf5-4abb-916c-14b8c8068538</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
