<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email address_input_email</name>
   <tag></tag>
   <elementGuidId>f4ca9aa0-da35-43b9-867d-527af465b820</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='input_email'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.form-group-inner.email.group.display--flex.flex--wrap.align-item--center.email-input.focusActive > input[name=&quot;input_email&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>60f8a920-00dc-4685-a5cd-0fb7880b3e08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputMaterial input-group</value>
      <webElementGuid>cfaa6437-38e7-48a7-ad2d-36ec8a79c98c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input_email</value>
      <webElementGuid>39a38174-5a90-4ca1-8c58-a1b86dbf0960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>098d9c79-9c70-4ff8-88bf-965bb98420ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contact-form&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;form-group-inner email group display--flex flex--wrap align-item--center email-input focusActive&quot;]/input[@class=&quot;inputMaterial input-group&quot;]</value>
      <webElementGuid>75fb8680-86a5-4339-916f-330d4aeede20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='input_email'])[2]</value>
      <webElementGuid>4e33c38f-a30a-4cd3-b668-499c2fb56641</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='contact-form']/div/div[2]/input</value>
      <webElementGuid>14faeb84-a964-43a5-b044-5678db939542</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>a77141e9-6471-4cda-86f1-7d45704a0b84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'input_email' and @type = 'email']</value>
      <webElementGuid>147e1e36-3e3c-450c-9db7-4ab197fbe14d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
