<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Full name_input_name</name>
   <tag></tag>
   <elementGuidId>27943ccc-e32c-4428-9813-0ff757d5168e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='input_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;input_name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>700124c4-f778-49e7-9cca-f1eb9e859324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputMaterial input-group</value>
      <webElementGuid>adef02dc-d163-49b0-8b92-aee425d33c70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input_name</value>
      <webElementGuid>f8b04bff-41cd-458e-a4e2-9d3515aa07de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>518e9583-a755-4c40-a09b-9ea770e82f4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contact-form&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;form-group-inner full_name group focusActive&quot;]/input[@class=&quot;inputMaterial input-group&quot;]</value>
      <webElementGuid>5d159237-8352-46d9-a890-a79c5dbb1413</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='input_name']</value>
      <webElementGuid>cdc01dd3-3b94-4074-a541-9ac77d526b67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='contact-form']/div/div/input</value>
      <webElementGuid>08dcaeb0-323a-4c51-8d34-f970c7a95d16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>3b964d12-e331-4649-b9e6-55e2a199b28f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'input_name' and @type = 'text']</value>
      <webElementGuid>9d6a2182-d7a2-4c1d-8da8-ad0bb78469f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
