<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Login failed_gsi_561610_624760</name>
   <tag></tag>
   <elementGuidId>d4b804e3-e6d6-4c4a-b1ba-341c2708b88f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gsi_561610_624760</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='gsi_561610_624760']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>78dae56f-e914-4026-8ac5-60f12fd05523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://accounts.google.com/gsi/button?type=standard&amp;shape=pill&amp;theme=outline&amp;text=signin_with&amp;size=large&amp;logo_alignment=left&amp;width=240&amp;client_id=864062262613-hbdrkfdijdf4o6chle9qirchhp6io4bm&amp;iframe_id=gsi_561610_624760&amp;as=pZNhOcnqrEWpk9blF7xY0w&amp;hl=en</value>
      <webElementGuid>9a58e528-984e-40ee-a6d3-0cd6ee48f727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gsi_561610_624760</value>
      <webElementGuid>e2751551-51b3-487b-aed6-0305d0179379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>زر تسجيل الدخول باستخدام حساب Google</value>
      <webElementGuid>f4b32f5a-ef5c-4cf6-a891-535fbf8d9cd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gsi_561610_624760&quot;)</value>
      <webElementGuid>d36bed59-3116-496a-a96a-3e58378e5942</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='gsi_561610_624760']</value>
      <webElementGuid>4b719780-036a-48cb-8669-28886bcb35bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='canidate-information']/div/div/div/div/div[3]/div/div[3]/div/iframe</value>
      <webElementGuid>ca044482-fcb8-4e74-ab93-a693df27acbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>c90ded3d-0e4f-4c56-829f-d42c43f187ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://accounts.google.com/gsi/button?type=standard&amp;shape=pill&amp;theme=outline&amp;text=signin_with&amp;size=large&amp;logo_alignment=left&amp;width=240&amp;client_id=864062262613-hbdrkfdijdf4o6chle9qirchhp6io4bm&amp;iframe_id=gsi_561610_624760&amp;as=pZNhOcnqrEWpk9blF7xY0w&amp;hl=en' and @id = 'gsi_561610_624760' and @title = 'زر تسجيل الدخول باستخدام حساب Google']</value>
      <webElementGuid>33a7ec64-033a-4c33-a783-1c9cc160e4bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
