<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Confirm My Choices_c-h1ey32cd11zo</name>
   <tag></tag>
   <elementGuidId>f04ab9c2-8cba-4396-98c6-5a03d81a9a95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;c-h1ey32cd11zo&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='c-h1ey32cd11zo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>5ebf203a-0c4f-4464-86f6-eb903779d617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>recaptcha challenge expires in two minutes</value>
      <webElementGuid>4a86e613-8e47-4492-b0a1-d7e5b59f6cb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>c-h1ey32cd11zo</value>
      <webElementGuid>2c8042b2-de75-49b0-b4ae-19c3b93a90f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9ec8f015-f256-444d-8e17-e18f5e8147fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>241f0695-a6e6-40ab-85c8-852a1f2494e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox</value>
      <webElementGuid>df40d318-36c6-4ace-8873-28a2767ca977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/bframe?hl=en&amp;v=lLirU0na9roYU3wDDisGJEVT&amp;k=6LfiRzcaAAAAAF18-SQqrsovqK5dd4V8T1rgfpyC</value>
      <webElementGuid>2a5d29e9-3831-40f7-8161-207d70b01ab8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;candidate-login&quot;]/div[9]/div[4]/iframe[1]</value>
      <webElementGuid>6f0e99bf-e324-4da4-a0a8-cdfdfb0b7229</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='c-h1ey32cd11zo']</value>
      <webElementGuid>f3f8f834-4dd7-4fbc-8bb8-d687b3f21e75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/iframe</value>
      <webElementGuid>3bb5f148-43b0-496d-ae55-e0a4f09f3622</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'recaptcha challenge expires in two minutes' and @name = 'c-h1ey32cd11zo' and @src = 'https://www.google.com/recaptcha/api2/bframe?hl=en&amp;v=lLirU0na9roYU3wDDisGJEVT&amp;k=6LfiRzcaAAAAAF18-SQqrsovqK5dd4V8T1rgfpyC']</value>
      <webElementGuid>e5ec3fb6-41fd-46b1-b792-e4f5ea8ac774</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
