<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1</name>
   <tag></tag>
   <elementGuidId>fe7d8482-c1f9-4cdb-ad4d-bf860adfe544</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[4]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6258a9b7-f148-40ee-86c8-f5efd8f7936c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>8ae2dbfe-f259-4a4e-8a82-c9ba5b64befa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA78d1pXfE3Ja--l32wAJxELAKamvfV_T4C67kpNx2XRG-bGyJyHI4jvC4lGrSsV8MGArv4t8OV3yprlg_y7lyUPN-rEoPyU0jrGMhtbmx98SNKO71wGOpzlGkzB4rqRluE7FcOSjgMi1y_YPMIO9sQ7DEFqxgXmS2wL4eaQNXynVAnFrxPT1f5OLuNcjeDRzfXwmWKv&amp;k=6LfiRzcaAAAAAF18-SQqrsovqK5dd4V8T1rgfpyC&amp;id=2</value>
      <webElementGuid>cbeca733-c83e-44fe-b2ee-aa5123e5a6d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>fb37bd12-e86d-488f-aeb2-7666f9abfd65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/UserOrderNewSinglePackage/Page_Login to Jobstoday.world - Create Resu_ef8a51/iframe_Confirm My Choices_c-h1ey32cd11zo</value>
      <webElementGuid>43c0d5e5-fd47-4564-ab87-b350716ebded</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[4]/div/div/img</value>
      <webElementGuid>0a94ec39-6cfd-43ab-902c-2947cc57e700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA78d1pXfE3Ja--l32wAJxELAKamvfV_T4C67kpNx2XRG-bGyJyHI4jvC4lGrSsV8MGArv4t8OV3yprlg_y7lyUPN-rEoPyU0jrGMhtbmx98SNKO71wGOpzlGkzB4rqRluE7FcOSjgMi1y_YPMIO9sQ7DEFqxgXmS2wL4eaQNXynVAnFrxPT1f5OLuNcjeDRzfXwmWKv&amp;k=6LfiRzcaAAAAAF18-SQqrsovqK5dd4V8T1rgfpyC&amp;id=2')])[12]</value>
      <webElementGuid>52d6054d-fbc9-4ef0-b89f-d11ed7d51adc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[4]/div/div/img</value>
      <webElementGuid>efca29e1-3fba-49e8-875b-1d136ecd488b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA78d1pXfE3Ja--l32wAJxELAKamvfV_T4C67kpNx2XRG-bGyJyHI4jvC4lGrSsV8MGArv4t8OV3yprlg_y7lyUPN-rEoPyU0jrGMhtbmx98SNKO71wGOpzlGkzB4rqRluE7FcOSjgMi1y_YPMIO9sQ7DEFqxgXmS2wL4eaQNXynVAnFrxPT1f5OLuNcjeDRzfXwmWKv&amp;k=6LfiRzcaAAAAAF18-SQqrsovqK5dd4V8T1rgfpyC&amp;id=2']</value>
      <webElementGuid>0f99dc51-9090-4f4f-86eb-ce2ed1804cd7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
