<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44</name>
   <tag></tag>
   <elementGuidId>a2438891-f029-4da9-ab3f-02b8a8a8b7f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>332767b9-c1c8-4eef-a689-ba88473c367c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>e74295ae-7071-4c99-9683-6c4b94318a00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA78d1pXfE3Ja--l32wAJxELAKamvfV_T4C67kpNx2XRG-bGyJyHI4jvC4lGrSsV8MGArv4t8OV3yprlg_y7lyUPN-rEoPyU0jrGMhtbmx98SNKO71wGOpzlGkzB4rqRluE7FcOSjgMi1y_YPMIO9sQ7DEFqxgXmS2wL4eaQNXynVAnFrxPT1f5OLuNcjeDRzfXwmWKv&amp;k=6LfiRzcaAAAAAF18-SQqrsovqK5dd4V8T1rgfpyC</value>
      <webElementGuid>41069e27-0ab9-4824-9b12-683285af9fc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>025c8068-a350-4674-9720-a47e90a8009a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/UserOrderNewSinglePackage/Page_Login to Jobstoday.world - Create Resu_ef8a51/iframe_Confirm My Choices_c-h1ey32cd11zo</value>
      <webElementGuid>ccbde709-7b30-4424-b545-417ab2308aa6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      <webElementGuid>7fd2e1a4-a5de-4b89-842e-4dca319cb70e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA78d1pXfE3Ja--l32wAJxELAKamvfV_T4C67kpNx2XRG-bGyJyHI4jvC4lGrSsV8MGArv4t8OV3yprlg_y7lyUPN-rEoPyU0jrGMhtbmx98SNKO71wGOpzlGkzB4rqRluE7FcOSjgMi1y_YPMIO9sQ7DEFqxgXmS2wL4eaQNXynVAnFrxPT1f5OLuNcjeDRzfXwmWKv&amp;k=6LfiRzcaAAAAAF18-SQqrsovqK5dd4V8T1rgfpyC')])[6]</value>
      <webElementGuid>fc4776c3-bec1-4931-aa4f-1028858ab614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/div/img</value>
      <webElementGuid>d20a906e-e7fb-4a40-b3d7-0a8ec0b43a9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA78d1pXfE3Ja--l32wAJxELAKamvfV_T4C67kpNx2XRG-bGyJyHI4jvC4lGrSsV8MGArv4t8OV3yprlg_y7lyUPN-rEoPyU0jrGMhtbmx98SNKO71wGOpzlGkzB4rqRluE7FcOSjgMi1y_YPMIO9sQ7DEFqxgXmS2wL4eaQNXynVAnFrxPT1f5OLuNcjeDRzfXwmWKv&amp;k=6LfiRzcaAAAAAF18-SQqrsovqK5dd4V8T1rgfpyC']</value>
      <webElementGuid>b5914c07-d8aa-4ed6-9ea3-23f8a59ab213</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
