<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Select</name>
   <tag></tag>
   <elementGuidId>b14dca86-fed1-4174-9b8d-9225dccbcc05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@onclick=&quot;$(this).parent().find('form').submit();&quot;])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.confirm-button-button.confirm-button-blue.button-buy.button-buy-onetime-enterprise</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>34f0cf46-b6ba-4f8e-beb3-fe293bfc610b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>abeaad8d-afbc-4c03-93b1-7c0639637ea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>$(this).parent().find('form').submit();</value>
      <webElementGuid>6ba4e36f-7d7b-4461-ad8d-6690c481758e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>confirm-button-button confirm-button-blue button-buy button-buy-onetime-enterprise</value>
      <webElementGuid>734138df-fcc8-4f6e-89af-10b2eb76de2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>b080adef-dc15-490e-989e-59e427c98c7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;pricing--page&quot;]/div[@class=&quot;main-content&quot;]/section[@class=&quot;pricing-section&quot;]/div[@class=&quot;page-wrapper-fulid&quot;]/div[@class=&quot;pricing-table-list&quot;]/div[@class=&quot;pricing-list-inner&quot;]/div[@class=&quot;pricing-single-tab single--tab-card&quot;]/div[@class=&quot;pricing--card-main&quot;]/div[@class=&quot;pricing--card single-pricing-card Enterprise-card&quot;]/div[@class=&quot;pricing-card-inner&quot;]/div[@class=&quot;select-button text--center&quot;]/a[@class=&quot;confirm-button-button confirm-button-blue button-buy button-buy-onetime-enterprise&quot;]</value>
      <webElementGuid>d236f257-9c01-47bd-a142-0ae93ae4869c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@onclick=&quot;$(this).parent().find('form').submit();&quot;])[2]</value>
      <webElementGuid>dd37a43e-d128-4f5a-9d95-a837ce9c1dae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Select')])[2]</value>
      <webElementGuid>ed0e2dc7-07c4-4ae4-a264-9bb3507ab1f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Priority Email Support'])[1]/following::a[1]</value>
      <webElementGuid>f48dfa58-be26-4263-a25f-3d555a68203d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Application Guarantee'])[2]/following::a[1]</value>
      <webElementGuid>52246b3b-8f6c-4467-94eb-6f3896ef9e13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Basic'])[1]/preceding::a[1]</value>
      <webElementGuid>16760d49-988d-4bc8-b97c-e49299e31c43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$ 299'])[1]/preceding::a[1]</value>
      <webElementGuid>51e59994-271e-4e22-93e8-40070c49f76f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[4]</value>
      <webElementGuid>26b92fd6-49cf-4596-871f-853a9d40c2a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/a</value>
      <webElementGuid>902134da-38eb-4e34-983c-a8d07feecec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>1025347d-7442-4a7d-a9ea-90f700b22d2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
