<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please enter cvc_privacy</name>
   <tag></tag>
   <elementGuidId>0dfb05f2-2d39-4e39-82fb-60abae7c804c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='privacy']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#privacy</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9f778a15-b340-4332-bbc8-2b4416263bf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>4dc1c23f-96ea-418d-be31-9db6fff8d61e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>privacy</value>
      <webElementGuid>e8747097-26f8-4678-85a5-0e65287e4f8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>privacy</value>
      <webElementGuid>8e47a215-e4de-4a65-abaa-3804eb040e34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;privacy&quot;)</value>
      <webElementGuid>22675619-2c34-41aa-bb00-1064e9025bfd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='privacy']</value>
      <webElementGuid>8fb6800b-5d74-4c07-ade5-9d9831e2afcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-checkout']/div/div/div/div[2]/div[4]/div/div/div/input</value>
      <webElementGuid>bb530189-469f-4696-b65a-02b972681027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/input</value>
      <webElementGuid>dc49f243-1f3c-46ad-85a7-bf05088fcb7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'privacy' and @name = 'privacy']</value>
      <webElementGuid>2e3b5ac1-c723-40c1-8337-0aae7aa6fd6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
