<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_cardnumber</name>
   <tag></tag>
   <elementGuidId>1d3e10c8-32c8-430c-b93f-3ac5b21cb331</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;root&quot;]/form/span[2]/span/div/div[2]/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;cardnumber&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c0a59dba-c28e-40aa-a254-29839086818f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>InputElement is-empty Input Input--empty</value>
      <webElementGuid>be0bed8f-8dd2-4142-83ad-4419b47ecd78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>cc-number</value>
      <webElementGuid>ddea065b-a57a-413a-b6e8-133be97a529d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>cf887280-91b0-43a6-ae03-5d83c6dca5c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9bfc00f9-d438-4bd9-bb17-6f9690a6e6ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7f153153-dc1f-4913-9596-80a3340ea7b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cardnumber</value>
      <webElementGuid>5ab50009-269d-4496-bdd0-2c958858adcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-elements-stable-field-name</name>
      <type>Main</type>
      <value>cardNumber</value>
      <webElementGuid>d34786d3-8f59-48f0-8e89-6a6dcf5455bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>734869af-b5ae-4757-87bf-31dbf9d94866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Credit or debit card number</value>
      <webElementGuid>dbbac93c-f458-4f43-b1de-a9d08be2fa7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Card number</value>
      <webElementGuid>df450213-6b4d-45ae-949d-45b4c8de94fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c27fc5e8-a7de-4b99-9636-bff060beed26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2568df51-0820-46b7-8552-edd885b7f420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/form[@class=&quot;ElementsApp is-empty is-focused&quot;]/span[2]/span[@class=&quot;SplitCardField is-link-hidden previous-link-hidden&quot;]/div[@class=&quot;CardNumberField CardNumberField--ltr&quot;]/div[@class=&quot;CardNumberField-input-wrapper&quot;]/span[@class=&quot;InputContainer&quot;]/input[@class=&quot;InputElement is-empty Input Input--empty&quot;]</value>
      <webElementGuid>f979a787-1f6e-4768-9cc9-d0124db795d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='cardnumber']</value>
      <webElementGuid>4cf4013b-e090-437a-83c5-d863ad4357ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/form/span[2]/span/div/div[2]/span/input</value>
      <webElementGuid>0bc69c37-bb70-404f-a666-c690fd20f06d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/input</value>
      <webElementGuid>2c78eb06-4390-4076-b05e-313957e4fd6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'cardnumber' and @placeholder = 'Card number']</value>
      <webElementGuid>1fb93268-4754-46ad-9bb3-8fba538f0595</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
