<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cardholder name_input_card_holder</name>
   <tag></tag>
   <elementGuidId>00b51398-43cf-426e-b153-0e5f3966bbbe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='input_card_holder']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;input_card_holder&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>70e3a9b3-6bc4-46ab-bed8-b6bb46dc1b08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>44bfa7b9-0177-42f2-a59e-8a063ff739fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input_card_holder</value>
      <webElementGuid>eea2f542-8503-475c-9c31-81369408dd90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cardholder name</value>
      <webElementGuid>1d4714c1-c7db-46ad-9800-2b09b8193006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-field</value>
      <webElementGuid>64d0775c-639b-419d-a7bf-0ffd060b27db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cc-card&quot;)/div[@class=&quot;form-group-global&quot;]/div[@class=&quot;form-inner display--flex flex--wrap align-item--center card-number&quot;]/input[@class=&quot;input-field&quot;]</value>
      <webElementGuid>ff0f00ee-cf7c-45aa-975d-f03e78649d9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='input_card_holder']</value>
      <webElementGuid>7a82c0ce-15fc-4ecc-baad-ab1781c2e9f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cc-card']/div[2]/div/input</value>
      <webElementGuid>c88b2892-9318-40ae-b2cb-c920466d0a44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>e70276c7-d209-489a-894c-a5bd2c50efba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'input_card_holder' and @placeholder = 'Cardholder name']</value>
      <webElementGuid>752533ca-4fd9-44e8-9e63-3bcd7cd8b618</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
