<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Select</name>
   <tag></tag>
   <elementGuidId>3b107a56-2261-4480-9c8e-ea60b2e95fa6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;$(this).parent().find('form').submit();&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.confirm-button-button.confirm-button-blue.button-buy.button-buy-onetime-starter</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e1a9dbde-2c12-4c6c-9f8f-008b4ce28f7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>eecffcde-19cb-42c1-8a31-154a6c791846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>$(this).parent().find('form').submit();</value>
      <webElementGuid>d0e796d9-25e5-48b4-820a-d2e9062444b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>confirm-button-button confirm-button-blue button-buy button-buy-onetime-starter</value>
      <webElementGuid>a4e05da6-4b5d-4df3-ba07-c0cf5f691989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>a943ae7b-5cd6-4840-8037-247c57ae6d30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;pricing--page&quot;]/div[@class=&quot;main-content&quot;]/section[@class=&quot;pricing-section&quot;]/div[@class=&quot;page-wrapper-fulid&quot;]/div[@class=&quot;pricing-table-list&quot;]/div[@class=&quot;pricing-list-inner&quot;]/div[@class=&quot;pricing-single-tab single--tab-card&quot;]/div[@class=&quot;pricing--card-main&quot;]/div[@class=&quot;pricing--card single-pricing-card&quot;]/div[@class=&quot;pricing-card-inner&quot;]/div[@class=&quot;select-button text--center&quot;]/a[@class=&quot;confirm-button-button confirm-button-blue button-buy button-buy-onetime-starter&quot;]</value>
      <webElementGuid>9d0d3e34-d100-4f3a-ba97-112339a3588f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;$(this).parent().find('form').submit();&quot;]</value>
      <webElementGuid>6fcfca3f-2db0-4b09-8083-5ab8f6dd223e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Select')]</value>
      <webElementGuid>fff719b3-dd78-46bd-86ee-3de2801f06d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Weekly Date Refresh'])[1]/following::a[1]</value>
      <webElementGuid>6570e8d7-c32b-44c6-b41c-d1cfa142ba40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Support'])[1]/following::a[1]</value>
      <webElementGuid>d1d17cb8-7575-4898-aad2-349116a48fa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enterprise'])[1]/preceding::a[1]</value>
      <webElementGuid>e58f73da-0260-4006-91fb-5063073add04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$ 0'])[2]/preceding::a[1]</value>
      <webElementGuid>8e9d2280-ef69-4895-87f3-7e06a8bb097f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select']/parent::*</value>
      <webElementGuid>be99448e-8e0b-433c-84b0-f0e9bf4be033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[4]</value>
      <webElementGuid>533cd555-fa46-478e-bff7-715defede786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>570dd56a-ce25-43db-9823-4f1cd09bca0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>252d02a8-3ccb-49d2-a104-b25e4d65381a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
