<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Select</name>
   <tag></tag>
   <elementGuidId>3b107a56-2261-4480-9c8e-ea60b2e95fa6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.confirm-button-button.confirm-button-blue.button-buy.button-buy-onetime-starter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//h2[text()='Starter'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>79c99c03-e1d8-4273-a0c2-e640310db908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>832c79b0-acc7-478f-b644-ac8ef1b0e765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>$(this).parent().find('form').submit();</value>
      <webElementGuid>ad54b8db-3cec-4c15-aa0c-fa59ac3a7208</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>confirm-button-button confirm-button-blue button-buy button-buy-onetime-starter</value>
      <webElementGuid>70fac695-5044-44b0-96ad-d0bb028daf27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>0695973f-628c-418e-991c-e6550ef0b2a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;pricing--page&quot;]/div[@class=&quot;main-content&quot;]/section[@class=&quot;pricing-section&quot;]/div[@class=&quot;page-wrapper-fulid&quot;]/div[@class=&quot;pricing-table-list&quot;]/div[@class=&quot;pricing-list-inner&quot;]/div[@class=&quot;pricing-single-tab single--tab-card&quot;]/div[@class=&quot;pricing--card-main&quot;]/div[@class=&quot;pricing--card single-pricing-card&quot;]/div[@class=&quot;pricing-card-inner&quot;]/div[@class=&quot;select-button text--center&quot;]/a[@class=&quot;confirm-button-button confirm-button-blue button-buy button-buy-onetime-starter&quot;]</value>
      <webElementGuid>39599b08-d533-4e63-ab0b-97037e38bb1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;$(this).parent().find('form').submit();&quot;]</value>
      <webElementGuid>4675bde7-3736-436e-baa0-480e490a094b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Select')]</value>
      <webElementGuid>4ed20053-ce27-4811-9667-3d33e224e064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Weekly Date Refresh'])[1]/following::a[1]</value>
      <webElementGuid>a705b221-22b3-49c7-a75d-c833e7b05feb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Support'])[1]/following::a[1]</value>
      <webElementGuid>f5e78bd0-6b53-479e-a4ce-ed8e36aa370d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enterprise'])[1]/preceding::a[1]</value>
      <webElementGuid>25c14cb6-3b45-497a-85ca-be63f7f6fbaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$ 0'])[2]/preceding::a[1]</value>
      <webElementGuid>bddcb484-57a2-4ddb-bfdd-01bb5c9325af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select']/parent::*</value>
      <webElementGuid>dd711dac-59a5-488f-9cad-f7ddc633df73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[4]</value>
      <webElementGuid>5e96d8af-4d62-4058-b177-dcadc6483ecc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>72186dd2-adfe-4ec1-ab60-77b9eed53d44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>a5e55b71-610f-41dc-9867-7bff71fcc504</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
