<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pricing</name>
   <tag></tag>
   <elementGuidId>e4ed4047-17f8-4d83-ba81-041c318071ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/div[3]/div/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.list-item-pricing > a.display--flex.align-item--center</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4c1dd01c-136b-4a12-8190-d6aef21cebd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>77044ad1-231f-40f3-aa4c-f09b237c48f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>display--flex align-item--center</value>
      <webElementGuid>9309732b-54fa-44cb-874d-73c10719fb82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Pricing 
                            </value>
      <webElementGuid>791382dc-44a5-442b-870f-0ef82fc68028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;header-menu&quot;]/div[@class=&quot;vertical-menu left--menu mobile-hidden&quot;]/ul[@class=&quot;display--flex&quot;]/li[@class=&quot;list-item-pricing&quot;]/a[@class=&quot;display--flex align-item--center&quot;]</value>
      <webElementGuid>4c31d70a-a5db-4fcc-8f9f-f66eb994965b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/div[3]/div/ul/li[3]/a</value>
      <webElementGuid>28012be6-f3b5-4069-8434-bd3be94e0557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Pricing')]</value>
      <webElementGuid>bea2090b-1b81-4dad-98ae-b79195c71d0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find Jobseekers'])[1]/following::a[1]</value>
      <webElementGuid>f98c5378-0099-4013-936c-e392262248f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find Jobs'])[1]/following::a[2]</value>
      <webElementGuid>3cc2dbe1-edf1-4595-a856-262393b1226b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='For employers'])[1]/preceding::a[1]</value>
      <webElementGuid>3e83381f-cfa3-42c9-8ff0-52596bf95fea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='For jobseekers'])[2]/preceding::a[2]</value>
      <webElementGuid>1ced0853-69bb-4f64-a00e-597328081945</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:;')]</value>
      <webElementGuid>d8e49d35-a8db-48d7-ac8d-aac7b11e7138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/ul/li[3]/a</value>
      <webElementGuid>fb820a18-4c0d-4d60-bff8-522ca52434e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = ' Pricing 
                            ' or . = ' Pricing 
                            ')]</value>
      <webElementGuid>dc0ce16e-ebf9-455b-ac7c-f8eb516dbae1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
