<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter valid password_confirm_password</name>
   <tag></tag>
   <elementGuidId>195308b4-9424-4a32-9c4b-4f5f5e6ad935</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='confirm_password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;confirm_password&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>220ef183-ea1a-420f-bf93-69b003cb9e29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>2c363fb0-8a3f-4914-9a77-ed9f876a9970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>.{5,60}</value>
      <webElementGuid>afba0987-29c8-466e-afbc-edb1ca4e35d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirm_password</value>
      <webElementGuid>5387380e-c022-4fda-a40f-1fc1281d5373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Confirm new password</value>
      <webElementGuid>b9558802-49ad-4e29-ba05-4b1c7a45309f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>e-input c-required</value>
      <webElementGuid>802034f5-755a-47cc-ac6e-80f8d3d3e1e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;changePassword&quot;)/div[@class=&quot;e-body&quot;]/div[@class=&quot;row-input&quot;]/div[@class=&quot;input-item _lg&quot;]/div[@class=&quot;input-wrap&quot;]/input[@class=&quot;e-input c-required&quot;]</value>
      <webElementGuid>d5408ad4-b183-44d6-9cf6-96a5a0bfd0b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='confirm_password']</value>
      <webElementGuid>c8836e76-06b2-4df3-a42c-8497883a3f58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='changePassword']/div/div[3]/div/div/input</value>
      <webElementGuid>acbba4b5-e152-485b-b400-a55108037009</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>fb26d8ca-8030-4324-b606-7ef43fe4f9e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'confirm_password' and @placeholder = 'Confirm new password']</value>
      <webElementGuid>83bc55e6-0183-4512-8060-091a83512abf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
