<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Got it</name>
   <tag></tag>
   <elementGuidId>4e5d7288-74a7-4068-ad8f-fcb51eda0cea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.button.button-no.button-priamry</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='successfully-registered']/div/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e882f8fa-d182-47ee-9e9c-cd8c8f2e7249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>a0493347-72d9-481b-b3d6-c76323a4845a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button button-no button-priamry</value>
      <webElementGuid>6593c623-d497-4e03-8ec2-582120559994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Got it</value>
      <webElementGuid>b858e097-55a4-445e-bc49-937d338de4fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;successfully-registered&quot;)/div[@class=&quot;success-login&quot;]/div[@class=&quot;confirm-button&quot;]/a[@class=&quot;button button-no button-priamry&quot;]</value>
      <webElementGuid>9993b17c-7684-4a91-9fad-ea67baeba685</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='successfully-registered']/div/div[2]/a</value>
      <webElementGuid>d162b1aa-20a0-4fa9-9db6-cf3e64c468a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Got it')])[2]</value>
      <webElementGuid>115593fa-770b-44f8-b16b-6bcc4bf59fdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You have successfully registered'])[1]/following::a[1]</value>
      <webElementGuid>41e7aa10-9248-4081-a3c5-de2c8214d3dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm My Choices'])[1]/following::a[2]</value>
      <webElementGuid>eda24067-858e-412a-82c5-4b5f84fbb55a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::a[1]</value>
      <webElementGuid>fac518c0-49f7-427c-9bd8-68b4b1c5cf7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[4]</value>
      <webElementGuid>fbfdaa01-81bc-499a-ba30-170bebde6aa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div[2]/a</value>
      <webElementGuid>11c65032-7125-4fe0-9833-516bac063d03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = 'Got it' or . = 'Got it')]</value>
      <webElementGuid>6230c7dc-dfaf-43ba-964c-4f7e931dca96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
