<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Website_privacy</name>
   <tag></tag>
   <elementGuidId>4cb62bf6-e7cd-4dec-8016-0f142954ddd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#privacy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='privacy']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>55382adf-44a2-499b-854a-e33e8bbf3975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>eb9039e4-c7e8-4d25-ad7b-7db28270c7b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>privacy</value>
      <webElementGuid>63a4f0a8-2299-4d01-aa40-d2d5276bb095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>privacy</value>
      <webElementGuid>cb44efd9-58ae-4093-8e2b-b19aa741e79d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;privacy&quot;)</value>
      <webElementGuid>4d9b5803-4dfa-4df1-9852-0f01fd134891</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='privacy']</value>
      <webElementGuid>31f1d9f3-583d-48dd-b9c4-0734aab6175f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='contact-form']/div[5]/div/div/div/input</value>
      <webElementGuid>d4eb2484-06de-4317-9e64-26f34a9bc013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/input</value>
      <webElementGuid>cf2a11b3-1a94-4660-a637-bbaf929f4402</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'privacy' and @name = 'privacy']</value>
      <webElementGuid>00c65415-995d-4291-9071-9050f0dcd550</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
