<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone number_input_phone</name>
   <tag></tag>
   <elementGuidId>55914183-37bc-4b5c-b5c3-56540152e3ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;input_phone&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='input_phone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f71ec92f-1d4f-48a9-873c-79ce4e0e681a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0317abe4-30fb-43e5-b3dc-afe204d6728b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input_phone</value>
      <webElementGuid>b953abfd-db79-4c84-ac3b-13e9a3e602bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-field</value>
      <webElementGuid>90e83c5a-cdc4-429a-a132-1793b3426bd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Prefix - Phone number</value>
      <webElementGuid>9a0bcb23-c446-4792-afff-3dfc2d81f291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contact-form&quot;)/div[@class=&quot;form-group-global display--flex&quot;]/div[@class=&quot;form-inner display--flex flex--wrap align-item--center&quot;]/input[@class=&quot;input-field&quot;]</value>
      <webElementGuid>84bcdbe7-02ea-4d9a-882d-da194716f8da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='input_phone']</value>
      <webElementGuid>94fdc99f-1635-41d8-aac8-76dfae6e71f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='contact-form']/div[3]/div/input</value>
      <webElementGuid>b332a557-867e-4ba1-835b-111cd0000f84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>c6b758b6-19aa-435e-a503-9f30eb0ddb95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'input_phone' and @placeholder = 'Prefix - Phone number']</value>
      <webElementGuid>9150ead3-b151-4ee0-8298-4d3c7905990b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
