<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Contact inquiry_input_inquiry</name>
   <tag></tag>
   <elementGuidId>917defe4-e142-4d66-95e0-66d6cfee26c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;input_inquiry&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='input_inquiry']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>493912a6-a12c-453b-83a6-1fa31a375047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-field</value>
      <webElementGuid>d0df60ac-b357-480b-bdd1-947f6d201ef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input_inquiry</value>
      <webElementGuid>16e7490f-581a-4d4f-9852-892f4ae966c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your message</value>
      <webElementGuid>41eced7e-6317-4a85-9f3f-e0569ac99b44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contact-form&quot;)/div[@class=&quot;form-group-global&quot;]/div[@class=&quot;form-inner display--flex flex--wrap align-item--center&quot;]/textarea[@class=&quot;input-field&quot;]</value>
      <webElementGuid>f25c9837-a36a-4f8d-9ff6-a5cba67c4ab8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='input_inquiry']</value>
      <webElementGuid>a082a1b9-ccfe-47d4-9869-089be0f3856b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='contact-form']/div/div/textarea</value>
      <webElementGuid>0cdcd9cd-f297-46ad-ab0f-6c461d223204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>25d8e0fb-ce7a-469e-8aef-7fbcc97ce589</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'input_inquiry' and @placeholder = 'Enter your message']</value>
      <webElementGuid>7c1d4454-d713-4322-85ba-b8d0a4fcc4cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
