<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Current email address_currentEmail</name>
   <tag></tag>
   <elementGuidId>9a9343ff-6eef-4749-9d44-2ed9a1f4a03a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='changeCurrentEmail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#changeCurrentEmail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b6a4983c-fb09-4020-a325-e8cdd80db2a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>changeCurrentEmail</value>
      <webElementGuid>60121423-5b22-45e2-afda-3315350ffbcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[+a-z0-9._-]+@[a-z0-9.-]+\.[a-z]{2,10}$</value>
      <webElementGuid>abfea9b0-e6fe-4a77-98d2-657ae8020a23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>7fc5f0ec-4523-430f-9c0b-28bc074c4c9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>currentEmail</value>
      <webElementGuid>c9d5a24a-ef8d-4d03-8c1e-5afca9715ee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>559d43ac-53df-4d61-9bb0-3d571ce6dd9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter current email address</value>
      <webElementGuid>abd6c4da-fc67-4d3e-8f6e-42d47db22b44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>e-input c-required</value>
      <webElementGuid>1c4cb6a2-0c1f-42aa-8020-7860eb6493f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;changeCurrentEmail&quot;)</value>
      <webElementGuid>4d6e7f7f-a1db-43df-afb5-904af61c69b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='changeCurrentEmail']</value>
      <webElementGuid>e8215e2e-bca3-4aa5-99ec-5957a1b1ffac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='changeEmailForm']/div/div/div/label/div[2]/input</value>
      <webElementGuid>9924d016-5be6-46c4-8531-e37c2b3e2275</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>5dd5f9da-9ee6-48d3-8560-ca6f10763cb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'changeCurrentEmail' and @name = 'currentEmail' and @placeholder = 'Enter current email address']</value>
      <webElementGuid>7051e189-b5de-497c-9906-264cb6beb29b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
