<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_New email address_newEmail</name>
   <tag></tag>
   <elementGuidId>c9b2f995-1938-460a-9b0e-ceaf1b7d9b34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='changeNewEmail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#changeNewEmail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>205f6373-232d-47bf-8595-23ddcd9adf3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>changeNewEmail</value>
      <webElementGuid>b51c110d-fea3-4c1b-86ab-a5543ae1606e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[+a-z0-9._-]+@[a-z0-9.-]+\.[a-z]{2,10}$</value>
      <webElementGuid>4ad28510-ab35-4771-aa42-6a623d59e46c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>5a791c15-cd47-45f5-9fca-870287097c4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>newEmail</value>
      <webElementGuid>d012f7ed-bd78-40d9-8592-02906e62dc6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>60c4610a-47f8-452f-9776-e354c5f66936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>old-email</name>
      <type>Main</type>
      <value>newtestem298@gmail.com</value>
      <webElementGuid>44d35048-792e-4f70-bf1a-fcbed378874b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter new email address</value>
      <webElementGuid>a39a6069-e763-4701-9ec1-ff8ac14cceb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>e-input c-required</value>
      <webElementGuid>6637d4f9-37c4-4347-b13f-6b41b7d72da8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;changeNewEmail&quot;)</value>
      <webElementGuid>94ab4c16-f063-431d-84ee-ed66701083f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='changeNewEmail']</value>
      <webElementGuid>9492c44c-0121-47df-948b-b9d09641830f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='changeEmailForm']/div/div[2]/div/label/div[2]/input</value>
      <webElementGuid>5bea5bf6-8e2f-4470-ae87-049b94a5cd0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/label/div[2]/input</value>
      <webElementGuid>ae453b9a-2f0c-486b-b8d6-2986530819a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'changeNewEmail' and @name = 'newEmail' and @placeholder = 'Enter new email address']</value>
      <webElementGuid>da9f4333-d2e2-4485-8488-56e19b4804d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
