<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Password_a-qwvu4kitlcdt</name>
   <tag></tag>
   <elementGuidId>e8db5915-b3d7-4b20-8ca6-23d411daf2a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-qwvu4kitlcdt&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-qwvu4kitlcdt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>488ca3c2-d65c-498f-bf81-590accf94567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>44f1bf7c-fe2c-4e73-b021-b6ff565026e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LfiRzcaAAAAAF18-SQqrsovqK5dd4V8T1rgfpyC&amp;co=aHR0cHM6Ly93d3cuam9ic3RvZGF5LndvcmxkOjQ0Mw..&amp;hl=en&amp;v=Ai7lOI0zKMDPHxlv62g7oMoJ&amp;size=normal&amp;cb=wkjq9v5ls700</value>
      <webElementGuid>77e693c4-b8ae-4d8f-b978-c294e1bdd608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>ea8b25e8-e4d7-45e8-a0db-76bf63c0f1e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>98b2ee32-6801-461c-b9f5-52fa84e74767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>6cb45796-851e-4f31-8009-51273f887233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-qwvu4kitlcdt</value>
      <webElementGuid>b37903f9-5479-43a6-aa35-81f271154969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>41766843-6610-4a3a-b5ea-d741a73b28e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>7c0a751f-cbdb-42de-87ae-6274365fdefa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox</value>
      <webElementGuid>35bc140d-3751-4910-a0d0-f10b771160c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g-recaptcha&quot;)/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>fbed0a4f-4cd6-4910-b91f-68aa7d710cda</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-qwvu4kitlcdt']</value>
      <webElementGuid>40ae7493-39a3-4bbb-8352-66f31b8e5cbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='g-recaptcha']/div/div/iframe</value>
      <webElementGuid>26e38da4-7745-4cb3-8d70-8bb90520aba5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>dcd7088b-e0a7-4575-8698-fd9428c0d60e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LfiRzcaAAAAAF18-SQqrsovqK5dd4V8T1rgfpyC&amp;co=aHR0cHM6Ly93d3cuam9ic3RvZGF5LndvcmxkOjQ0Mw..&amp;hl=en&amp;v=Ai7lOI0zKMDPHxlv62g7oMoJ&amp;size=normal&amp;cb=wkjq9v5ls700' and @name = 'a-qwvu4kitlcdt']</value>
      <webElementGuid>eb29532b-bd82-4177-9602-ef2d0fe07371</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
