<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email address_input_email</name>
   <tag></tag>
   <elementGuidId>57f8abbb-2a93-426e-95d2-d9d32a723ef4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#login_email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='login_email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>24757602-3106-4f1e-8640-7ede52410b09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>ea064d37-bc60-49cc-8b1a-c3511da0ece8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input_email</value>
      <webElementGuid>6336c75e-e67c-4ff8-ace8-3d4cf5ac2da8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login_email</value>
      <webElementGuid>a314d722-a3ef-4972-ab77-348a1919e254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email address</value>
      <webElementGuid>3e9377e7-9d87-4bf4-8c56-b21590db81b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-field</value>
      <webElementGuid>a97c142e-b362-42fd-a5ba-4985adeaee0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login_email&quot;)</value>
      <webElementGuid>5f1ae9db-2be6-4baa-83a5-ed2368bb7890</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='login_email']</value>
      <webElementGuid>cfad2092-346c-4d97-b4a5-da376f3cae6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='candidate-login']/div/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>9de8ebfc-c49b-438c-8bdd-752124f99019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>1876194f-947d-4737-ab64-880c70195927</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'input_email' and @id = 'login_email' and @placeholder = 'Email address']</value>
      <webElementGuid>b1bbea3c-5adc-45f5-a444-9b5a5c692af3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
