<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Attachments_upload-photos-box</name>
   <tag></tag>
   <elementGuidId>5c01ad25-7dde-4588-bbef-0ef077fef3fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#upload-photos-box</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='upload-photos-box']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0a4fe2af-8351-4370-9df8-38f8976550cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>upload-photos-box</value>
      <webElementGuid>a612d6c3-dba9-4b0f-b29b-294d59538047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>image_select image-select-first dz-clickable</value>
      <webElementGuid>eb54404d-3a3c-4fad-acb4-7726f2e53f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-apply_job&quot;)/div[@class=&quot;form-head&quot;]/div[@class=&quot;interesting-form&quot;]/div[@class=&quot;interesting-form-inner&quot;]/div[@class=&quot;form-group display--flex flex--wrap align-item--center file-attach&quot;]/div[@class=&quot;form-inner display--flex flex--wrap align-item--center cover-letter&quot;]/div[@class=&quot;attachments&quot;]/div[@class=&quot;file-attach&quot;]/div[@id=&quot;upload-photos-box&quot;]</value>
      <webElementGuid>a2c0c97a-0abc-467d-b5c1-3cc021fdf912</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='upload-photos-box']</value>
      <webElementGuid>0f2606a4-19f3-4871-9ebe-be519c51edc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-apply_job']/div/div[2]/div/div[4]/div/div[2]/div/div</value>
      <webElementGuid>41fcbdcd-753e-43ce-ae16-b423e7cdabb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/div</value>
      <webElementGuid>f3883f1d-ac75-46e4-99ce-116056bf2d8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'upload-photos-box']</value>
      <webElementGuid>ad416738-e62b-4168-82ac-2f894e9472c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
