<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Cover letter  Brief description ab_6b68b0</name>
   <tag></tag>
   <elementGuidId>b5fe950a-5865-471f-851d-999f4e9023b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;input_cover_letter&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='input_cover_letter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>2857ba12-a974-47bc-9f78-b4f5178767a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-field</value>
      <webElementGuid>43ad8798-9f00-420f-9e07-6faa753858a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>row</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>dce0e8dd-5486-45ba-ac91-56d088adc5a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input_cover_letter</value>
      <webElementGuid>5fd93068-6279-446c-a6eb-c70509cd2202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Compose a cover letter for employer</value>
      <webElementGuid>d2e55717-efb1-4fa3-8bd4-f9086d3f5fc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-apply_job&quot;)/div[@class=&quot;form-head&quot;]/div[@class=&quot;interesting-form&quot;]/div[@class=&quot;interesting-form-inner&quot;]/div[@class=&quot;form-group display--flex flex--wrap align-item--center text-area&quot;]/div[@class=&quot;form-inner display--flex flex--wrap align-item--center cover-letter&quot;]/textarea[@class=&quot;input-field&quot;]</value>
      <webElementGuid>5ddce16a-a1c6-4e8c-a214-07ad3cf2af21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='input_cover_letter']</value>
      <webElementGuid>5dd0c775-8793-443c-b3a4-04089a81a4aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-apply_job']/div/div[2]/div/div[3]/div/textarea</value>
      <webElementGuid>2e82cce1-4baa-4d80-8f76-0d98f38df31c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>93c8d2b3-7e1c-4e9c-9562-5a5a780d9219</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'input_cover_letter' and @placeholder = 'Compose a cover letter for employer']</value>
      <webElementGuid>8acb4835-a607-43f6-900f-f858528b25ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
