<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Post Now</name>
   <tag></tag>
   <elementGuidId>ef7296e1-90db-4c2e-a730-83e0e0319abc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn-dark.button_unique_post_jobseeker</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick=&quot;$(this).parent().find('form').submit();&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fb74f7d1-18c2-4146-8ba7-8b0da8ff0c88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-dark button_unique_post_jobseeker</value>
      <webElementGuid>40cbabfa-57c4-4317-a5e1-679129e38c75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>$(this).parent().find('form').submit();</value>
      <webElementGuid>1ff39c17-93bb-477e-bc92-85faa5349653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Post Now</value>
      <webElementGuid>b4f271b2-93d7-47b7-85f8-9f65b64da981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;jobseeker-service-provider-landing-page pricing--page&quot;]/div[@class=&quot;main-content&quot;]/section[@class=&quot;js-sp-banner-section&quot;]/div[@class=&quot;js-banner banner-main&quot;]/div[@class=&quot;info-section banner-inner&quot;]/div[@class=&quot;price-section&quot;]/div[@class=&quot;form-group-global btn-section&quot;]/button[@class=&quot;btn-dark button_unique_post_jobseeker&quot;]</value>
      <webElementGuid>3401ab29-35fc-4641-97c5-d128cfbaa0c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick=&quot;$(this).parent().find('form').submit();&quot;]</value>
      <webElementGuid>3e7b9261-4874-4416-be50-b33222fc70b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More info'])[1]/following::button[1]</value>
      <webElementGuid>ac1c64b9-e495-4b6e-aecf-7dee0dde6740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$ 0.00'])[1]/following::button[1]</value>
      <webElementGuid>52eb44e7-124a-4c08-99af-9fffd46ce3e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drop your email to receive special offers and discounts'])[1]/preceding::button[1]</value>
      <webElementGuid>77f52206-3ab2-498c-9111-2f0dd6f0da30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subscribe'])[1]/preceding::button[1]</value>
      <webElementGuid>e9369810-f9b3-4cc2-85ec-1c5569fdd805</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Post Now']/parent::*</value>
      <webElementGuid>fadc80f2-6f3f-40e5-8d68-cff12621c075</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>d2f55f9f-8375-4044-993f-386312de43fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Post Now' or . = 'Post Now')]</value>
      <webElementGuid>e0950053-9083-405a-ab3e-b6b1d018eaa6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
