<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First name_input_firstname</name>
   <tag></tag>
   <elementGuidId>de5fe696-9c5e-4be0-a6a3-135b3b9755b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;input_firstname&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='input_firstname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a89f9090-60a3-4dfc-893f-b9f8503562fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c614b26a-fbd9-4fb8-a578-14236ace96a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input_firstname</value>
      <webElementGuid>6c737b41-9e56-4285-a681-58d7202d5778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>First name</value>
      <webElementGuid>098fca06-6cc1-4e91-b6c4-4f590092c323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-field</value>
      <webElementGuid>67886b39-1177-4dc4-b179-fa5f9927e593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;premium-jobseeker-form&quot;)/div[@class=&quot;form-group-global display--flex flex--wrap&quot;]/div[@class=&quot;form-inner display--flex flex--wrap align-item--center&quot;]/input[@class=&quot;input-field&quot;]</value>
      <webElementGuid>98566f27-d78c-4eee-b7cc-cd517cde9c6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='input_firstname']</value>
      <webElementGuid>2cd8057d-2359-4874-8766-9148a51bc57c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='premium-jobseeker-form']/div/div/input</value>
      <webElementGuid>24a7e066-2a40-4cef-be9f-b575f186c853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f04d66d6-8d90-48c5-8edc-517a767fb86c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'input_firstname' and @placeholder = 'First name']</value>
      <webElementGuid>2a2d79ce-629a-476e-96d9-1834a1fd777a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
