<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_I am looking for a job_input_job</name>
   <tag></tag>
   <elementGuidId>8d812bae-b141-421b-abc0-cb320ea5957e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;input_job&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='input_job']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>65fe6dc7-2842-49ea-be83-91c0f27ecdf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-field</value>
      <webElementGuid>86ab75f3-1983-4f53-b8b1-d374ebf18400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input_job</value>
      <webElementGuid>814240ac-4111-4dd7-89f8-906e1d3a103f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Describe the job you're looking for. For example: I am looking for a job as cook/warehouse worker/designer.</value>
      <webElementGuid>ac0bc133-a0cf-42f4-8f20-43c462b734c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;premium-jobseeker-form&quot;)/div[@class=&quot;form-group-global display--flex flex--wrap p-sides&quot;]/textarea[@class=&quot;input-field&quot;]</value>
      <webElementGuid>abc42258-54ee-4d51-af1b-668016643ced</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='input_job']</value>
      <webElementGuid>dbc82ecc-6e11-4c6e-92ff-c9aeefa52046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='premium-jobseeker-form']/div[3]/textarea</value>
      <webElementGuid>4066708c-681f-40d3-844b-285c70ecf77e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>c4a9b594-4084-4779-9b39-6725fd1bc494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'input_job' and @placeholder = concat(&quot;Describe the job you&quot; , &quot;'&quot; , &quot;re looking for. For example: I am looking for a job as cook/warehouse worker/designer.&quot;)]</value>
      <webElementGuid>cc5c76f9-b80c-43f2-a859-b18e2526cb8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
