<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PL_keywords</name>
   <tag></tag>
   <elementGuidId>9d5d7842-0bb1-4ec5-8d85-1812567f5884</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#keywords</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='keywords']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8505600e-248f-482d-978f-e9068ff54125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>21ee0a97-6cc5-41fc-ace3-6e5c7f309183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form--inner ui-autocomplete-input</value>
      <webElementGuid>ddf22975-7eec-4a81-8645-870b978200b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>keywords</value>
      <webElementGuid>e76358ca-1bda-4480-add5-2e83206a9fbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>keywords</value>
      <webElementGuid>9d882a86-a8db-4350-89d8-4d6c582701fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search jobs by keyword</value>
      <webElementGuid>a922eeeb-3207-4812-84ab-f6ef019c3735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f7b37748-ee42-4e6c-a6eb-ae481b9882d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;keywords&quot;)</value>
      <webElementGuid>968357c6-f693-4580-8567-9b78cb386f55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='keywords']</value>
      <webElementGuid>15b170a6-5a71-42fd-aa1a-b6fa283bd02a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchForm']/div/div/input</value>
      <webElementGuid>616a21f3-29c1-48bb-95d6-c6804439c77c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>c70abd77-8edf-4745-b63a-74bdc6737b22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'keywords' and @id = 'keywords' and @placeholder = 'Search jobs by keyword']</value>
      <webElementGuid>7c60f98f-18c4-46ed-aaae-e95ac9a249c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
