<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>searchButton</name>
   <tag></tag>
   <elementGuidId>5b52fa96-a624-4fa8-8d6f-40f9c11aca4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[contains(@class,'search-btn')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3899af13-bbde-447d-874d-bbcae35d9dd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/images/icon/search-white.svg</value>
      <webElementGuid>3ba0aa5d-9927-48f2-981f-03d9fc42ebe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchForm&quot;)/div[@class=&quot;search_form display--flex flex--wrap align-item--center active-job--serach&quot;]/div[@class=&quot;search--icon apply_button&quot;]/button[1]/img[1]</value>
      <webElementGuid>a7c07231-e7f0-41b2-83b9-f2548154e200</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchForm']/div/div[3]/button/img</value>
      <webElementGuid>fdd112b3-3962-44c6-93b7-e087d9503feb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/img</value>
      <webElementGuid>c017bb0a-8cac-4888-8c29-d3a86d058ace</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/images/icon/search-white.svg']</value>
      <webElementGuid>827ae379-0c35-4da9-a814-3dfcfe60e5b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
