<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select currency</name>
   <tag></tag>
   <elementGuidId>af80399f-325c-4b04-ab45-5c1efb459296</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-currency-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-currency-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cafbbd4a-7d89-4778-8a6d-b905b3a91b26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>21d627fd-8e9a-405a-85ba-7e29db546fed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-currency-container</value>
      <webElementGuid>27cb0f2a-0a0f-4958-9cf4-98cb5ce27ae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>5ce01755-2f41-4d40-a5d0-78d4b413fd83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>169ea826-50dd-4e98-b57b-ffe7e54c6892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>
                                                                        Select currency                                                                    </value>
      <webElementGuid>f26350aa-a814-4ce1-9fd1-37baacadd18b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                        Select currency                                                                    </value>
      <webElementGuid>d040c814-5143-406b-bd14-44851b592031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-currency-container&quot;)</value>
      <webElementGuid>29f900ee-894d-4aa8-bccd-7424ee70022d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-currency-container']</value>
      <webElementGuid>bb06553c-aedb-4a35-8e21-8180fa6e68cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='myform-p-0']/div/div/div[2]/div[4]/div/div/span/span/span/span</value>
      <webElementGuid>f91b3c5d-45ee-4660-bca3-905d03811a70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Currency'])[1]/following::span[4]</value>
      <webElementGuid>08daf4d5-8c5d-4f54-9988-468188cb79f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Specify yearly salary or hourly/daily rate.'])[1]/preceding::span[4]</value>
      <webElementGuid>5eb29688-53d7-42ee-880f-4373e1d17f81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/span/span/span/span</value>
      <webElementGuid>043fddd2-caba-40b0-bf1f-e410fa6982e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-currency-container' and @title = '
                                                                        Select currency                                                                    ' and (text() = '
                                                                        Select currency                                                                    ' or . = '
                                                                        Select currency                                                                    ')]</value>
      <webElementGuid>4f18ad40-d725-491b-a89f-0d7e67243af3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
