<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select communication language</name>
   <tag></tag>
   <elementGuidId>8ac3865d-10bc-49aa-807d-dad93a627ceb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-input_communication_language-eg-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-input_communication_language-eg-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fa89ea30-e531-4a03-97f2-cabe94021884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>976f168a-924f-4f76-a696-30f0547bb5d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-input_communication_language-eg-container</value>
      <webElementGuid>39f67715-f4c1-47f9-bb9c-b32c8255dd27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>04537847-a462-4dba-b3e8-5b9ef48ca198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>41ceac5c-ac66-4bcc-880a-2da8613adf81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select communication language</value>
      <webElementGuid>d0d65a9c-335c-4222-b6db-50330d594b55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-input_communication_language-eg-container&quot;)</value>
      <webElementGuid>1838b9ab-19f4-4781-b6b4-2ea00d3237ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-input_communication_language-eg-container']</value>
      <webElementGuid>ec6d9856-19ca-49d6-b478-7fe5b4809033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-checkout']/div/div/div/div/div[3]/div[7]/div/span/span/span/span</value>
      <webElementGuid>037078d7-1b75-44dd-8efb-2934d41f191a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Animals'])[2]/following::span[8]</value>
      <webElementGuid>213495a8-eced-4222-b7a7-9ac8ebca8917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/span/span/span/span</value>
      <webElementGuid>59f10597-7176-4a03-aac2-a9a2c7ca1040</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-input_communication_language-eg-container' and (text() = 'Select communication language' or . = 'Select communication language')]</value>
      <webElementGuid>4243c513-8666-4700-8784-ab437706be93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
