<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select industry</name>
   <tag></tag>
   <elementGuidId>e48b042f-ad04-4d5b-816a-a4619f9d6802</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-industry-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-industry-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>eaa52121-318e-4ebf-ba05-4c0c7be625ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>d53e5ec8-5c2a-4b95-a5f4-6f9c2a0d06ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-industry-container</value>
      <webElementGuid>f428e1d3-014b-46de-9a99-1f685d48e45a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>4b910f67-4122-4f94-879b-ecbc63789968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a4c773b7-ce5c-4ddd-b629-d6388bc40f76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select industry</value>
      <webElementGuid>2b366158-d640-4adf-a1f2-c6c6bffeb3da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-industry-container&quot;)</value>
      <webElementGuid>4ab74fa4-d284-446d-bc6b-49acf9032eb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-industry-container']</value>
      <webElementGuid>8f68dbe3-e337-41ef-a7f7-7c074a059359</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-checkout']/div/div/div/div/div[3]/div[6]/div[2]/div/span/span/span/span</value>
      <webElementGuid>b916ddb1-7b6d-4bde-b0c4-e01b75b1d271</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recruitment Agency'])[2]/following::span[7]</value>
      <webElementGuid>c8b5a645-29cd-4b8c-aeb6-f7df117bfd20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/span/span/span/span</value>
      <webElementGuid>82bbe049-6aa6-4e4f-abb7-bb2386caeb75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-industry-container' and (text() = 'Select industry' or . = 'Select industry')]</value>
      <webElementGuid>05027d9a-9aed-46f6-9143-043436b79c09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
