<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Describe in few words the most imp_0f1197</name>
   <tag></tag>
   <elementGuidId>c37c8a02-acbd-427a-9a53-da312b022472</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CompanyDescription</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='CompanyDescription']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>3934621b-0ada-4974-ace3-78132a011788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>dac87dce-a65f-489a-9f41-0e4426ea0d4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>row</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>283d4cc0-b270-4313-aa1e-7ef1d03b36f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CompanyDescription</value>
      <webElementGuid>ba742ef4-fe78-4401-9c96-ade67b07aea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CompanyDescription</value>
      <webElementGuid>618ba910-bafc-4945-86de-04196bb527f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter a short company description (minimum 50 characters)</value>
      <webElementGuid>89819c79-28e2-4877-bda4-8cff28c22b34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CompanyDescription&quot;)</value>
      <webElementGuid>346f5d04-0b20-4133-850d-50c064f805f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='CompanyDescription']</value>
      <webElementGuid>0739cfdc-f18d-48e7-b5fe-97bf6c29e4ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='myform-p-0']/div/div/div/div[5]/div/textarea</value>
      <webElementGuid>a9108fc9-ebfb-43f6-8c0f-cabc7f7b3140</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>ba88e7cf-41d3-4ae0-abeb-5d6e660db798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'CompanyDescription' and @id = 'CompanyDescription' and @placeholder = 'Enter a short company description (minimum 50 characters)']</value>
      <webElementGuid>3446804e-b089-4504-9126-1a4adb7e1436</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
