<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Enter a short Job description, it _305c38</name>
   <tag></tag>
   <elementGuidId>484d4d89-0da0-442f-afc4-a08999a5e97e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#short_description</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;short_description&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>82fdcf7f-6a75-4807-a4f5-20fd926e43a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1f128093-c666-42b0-856d-ed8351090681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>row</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>a219de0a-a4d2-4a82-87c4-6eccd238ebc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>short_description</value>
      <webElementGuid>33aa7c14-3203-4fb4-afed-8aee6bf3d0a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>short_description</value>
      <webElementGuid>4b5b5126-2712-4a0c-96c4-ee9ed7705f03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Job description (min 50 characters)</value>
      <webElementGuid>83c0acb0-d19f-4f83-8abf-adfbdc627bbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;short_description&quot;)</value>
      <webElementGuid>af9e74c9-001f-4e3f-8bbd-19149d406a0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='short_description']</value>
      <webElementGuid>949dc924-3376-4066-9a35-b82f9806e141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='myform-p-0']/div/div/div/div[7]/div/textarea</value>
      <webElementGuid>1433d9f0-ba94-4220-b286-68afcc4c2327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/textarea</value>
      <webElementGuid>7b0b160b-447d-495c-9530-0e68f3f684ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'short_description' and @id = 'short_description' and @placeholder = 'Enter Job description (min 50 characters)']</value>
      <webElementGuid>f0b73ffc-79c6-41ee-8fed-f2f8350c64a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
