<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Online_b-btn-delete c-modal__bind</name>
   <tag></tag>
   <elementGuidId>9a429862-91f6-4fb4-9084-045aa285d92c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.b-btn-delete.c-modal__bind</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//td[contains(@class,'b-company-admin-panel-table__cell_last')] /div /div[2] /button)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f61cccf9-445f-484e-8937-d86351e6b064</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>74a1709a-7266-4227-8e55-732c90739623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>$('.deleteJob').attr('data-jobid', 21297916)</value>
      <webElementGuid>d0ae6e3a-b19e-4373-b20a-0767f8c0887e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-c-modal-number</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>b520b521-24b9-49e6-99e5-798d5ad23595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>b-btn-delete c-modal__bind</value>
      <webElementGuid>a6d4dced-95d4-463b-a9ba-e6cec7f60944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;job_21297916&quot;)/td[@class=&quot;b-company-admin-panel-table__cell b-company-admin-panel-table__cell_last&quot;]/div[@class=&quot;b-options-list b-options-list_indent_horiz_sm b-options-list_inside_table&quot;]/div[@class=&quot;b-options-list__item b-options-list__item_last&quot;]/button[@class=&quot;b-btn-delete c-modal__bind&quot;]</value>
      <webElementGuid>c6f91b0e-e02f-40c8-84bd-88be77a4f2fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick=&quot;$('.deleteJob').attr('data-jobid', 21297916)&quot;]</value>
      <webElementGuid>146de75f-1d3b-4f9e-ab8e-655e9f7350cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='job_21297916']/td[10]/div/div[2]/button</value>
      <webElementGuid>3fa0f1bf-3349-4be9-8a22-07c98d4e57a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[10]/div/div[2]/button</value>
      <webElementGuid>f8cce4d5-7c0a-47e1-a9b7-f7c29599aade</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@href = '#']</value>
      <webElementGuid>6c4c8299-fd88-4378-b2fa-8e41000cf6ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
