<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_City  Country_input_city_country</name>
   <tag></tag>
   <elementGuidId>d709ec11-3f6b-45d5-948f-aa2937f09f03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#location</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='location']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>368fc421-59b7-49b3-862a-3a2575cd5905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>location</value>
      <webElementGuid>20aa6534-9ac9-48b4-ae0c-451c5b109f44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>937d4262-9a6b-41e4-9b33-5505ddf236cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input_city_country</value>
      <webElementGuid>ec432c2f-b22e-454a-9613-c9ce018cbfcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>City &amp; Country</value>
      <webElementGuid>25c0b27a-732b-44ad-a83f-516b5d2748f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-field pac-target-input</value>
      <webElementGuid>44151cd3-87c6-4014-9995-28e9c0ad40f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0b3447aa-680a-4e14-b234-de2417958eae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;location&quot;)</value>
      <webElementGuid>69ccb61f-337f-4d20-bce0-c1b21010f9f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='location']</value>
      <webElementGuid>ab66ef41-beb8-4c9d-9177-7b131fa5ad0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-checkout']/div/div/div/div/div[3]/div[4]/div[2]/input</value>
      <webElementGuid>e5651378-703c-4a1a-bc24-e8368f72813b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/input</value>
      <webElementGuid>4a543777-fb61-4d1d-95c2-0211e0087d84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'location' and @type = 'text' and @name = 'input_city_country' and @placeholder = 'City &amp; Country']</value>
      <webElementGuid>38126f3e-0858-4e41-82fd-2d7536a767e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
