<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Salutation</name>
   <tag></tag>
   <elementGuidId>1aa0de73-075a-4a67-a39c-77d9ddacdeee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-input_title-ad-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@data-select2-id='4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>63529822-4678-42fa-acdd-dbfb36482c7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>2e9f55e4-ea1d-4862-a734-d050f630b795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-input_title-ad-container</value>
      <webElementGuid>06a47867-74e7-4027-a207-fd60c93ce321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>256639fd-33a2-4dca-9b79-05c9e743493c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ed37efa5-8cc2-4de8-80b6-1254c2299b1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Salutation</value>
      <webElementGuid>e93c4e60-2132-41f2-a790-5842718c5d19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-input_title-ad-container&quot;)</value>
      <webElementGuid>1acf9df7-b488-4830-ac5d-a288c2fb987b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-input_title-ad-container']</value>
      <webElementGuid>3549d37e-8a3d-4ffc-9269-26c94d199785</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-checkout']/div/div/div/div/div[3]/div[2]/div/span/span/span/span</value>
      <webElementGuid>352de3e3-b925-4848-a3c2-de07f00eecc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salutation *'])[1]/following::span[4]</value>
      <webElementGuid>7c29b889-67ab-4326-ad1d-0f1b78c0da87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='At least 8 characters long'])[1]/following::span[4]</value>
      <webElementGuid>de632a43-0e81-4362-8570-09812be9c2fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>3578a29c-86da-4b40-b1b7-4ed3425b22f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-input_title-ad-container' and (text() = 'Salutation' or . = 'Salutation')]</value>
      <webElementGuid>20326630-d719-49d9-8751-c912cf2fae4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
