<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_input_password</name>
   <tag></tag>
   <elementGuidId>21057f0f-9df6-4eca-93fe-6d4b46b234df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#login_password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='login_password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>69013f05-4ada-450a-a395-021cbab4d4e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>93d0f88f-bbe9-484d-833e-278dc2a304d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input_password</value>
      <webElementGuid>68e9fcb5-981e-4d66-a94c-87a49b7a5e77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login_password</value>
      <webElementGuid>a28400f3-715d-4de1-9c87-cb4fb46ce9fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>b33a2aaa-4317-426b-ad3f-7fdaa25be58b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-field</value>
      <webElementGuid>855bc133-4c63-45bd-939a-1726636f8f9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login_password&quot;)</value>
      <webElementGuid>7d7abe21-5dc3-418b-a355-4ac4f8d6838d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='login_password']</value>
      <webElementGuid>9c02c4e4-07ad-4f99-817f-71f07c8d17f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='candidate-login']/div/div/div/div/div[2]/div/div[2]/input</value>
      <webElementGuid>0437ecbc-a0c7-4d7d-9710-a6ce928aa82c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>657bebbb-ae20-4893-b6c2-5676ba625751</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'input_password' and @id = 'login_password' and @placeholder = 'Password']</value>
      <webElementGuid>2c5c2c07-abb1-4b82-9478-5a63ef800397</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
