<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Verify</name>
   <tag></tag>
   <elementGuidId>4368438b-cdad-4482-8d80-84e23b6a100a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#recaptcha-verify-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='recaptcha-verify-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3aa0f955-4473-4f53-b1ef-92d6f07d9061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-button-default goog-inline-block</value>
      <webElementGuid>6e73e1d6-0163-422c-8a75-0e26699ef668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>recaptcha-verify-button</value>
      <webElementGuid>1d483806-aadc-4067-8811-de62e2cf7387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7d6475ac-356e-46f1-96b1-b5164ff222bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Verify</value>
      <webElementGuid>3e2cc8df-456d-41de-a9c6-49fca87391dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recaptcha-verify-button&quot;)</value>
      <webElementGuid>e10b2d17-e10f-4b3a-ac7e-de79bd2b3cb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/CreateResume/Page_Login to Jobstoday.world - Create Resu_ef8a51/iframe_Confirm My Choices_c-xa1darhv5rqs</value>
      <webElementGuid>109b34cf-e7ca-4ad2-8d56-2ac0cf6c6911</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='recaptcha-verify-button']</value>
      <webElementGuid>952b3a5a-7a87-4097-94ec-1d5d0995b6d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect']/div[3]/div[2]/div/div[2]/button</value>
      <webElementGuid>3b5f5209-b457-40a0-bb3e-3c1bbebd8759</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click verify once there are none left.'])[1]/following::button[6]</value>
      <webElementGuid>6d4b205f-33d4-478c-a18a-3998fd30d53e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='crosswalks'])[1]/following::button[6]</value>
      <webElementGuid>78ca2ce9-97e1-4ecb-83a2-61e22d67948c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'recaptcha-verify-button', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>ae68a20a-8419-4ee7-b551-6addd22901fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Verify']/parent::*</value>
      <webElementGuid>f3205e7b-9505-477d-90e0-0297f24762ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>c9637316-bc31-4913-9a47-5637e4684fc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'recaptcha-verify-button' and (text() = 'Verify' or . = 'Verify')]</value>
      <webElementGuid>7f9408fe-ef27-42a2-ab6d-a636fd5a2940</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
