<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Password_a-xa1darhv5rqs</name>
   <tag></tag>
   <elementGuidId>cbd3bac0-be95-4022-96fa-17bc372ff35b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-xa1darhv5rqs&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-xa1darhv5rqs']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>734f03ac-f1b4-4f48-8dd2-820c1eef0885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>7447da94-21c0-4362-b688-0f9548c9930c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LfiRzcaAAAAAF18-SQqrsovqK5dd4V8T1rgfpyC&amp;co=aHR0cHM6Ly93d3cuam9ic3RvZGF5LndvcmxkOjQ0Mw..&amp;hl=en&amp;v=IqA9DpBOUJevxkykws9RiIBs&amp;size=normal&amp;cb=o01wiuvb0spf</value>
      <webElementGuid>2cf8b4ad-c481-4c26-a80c-50bc1210cfc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>a06e6820-feb7-4699-a1e2-92166033db84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>5b08e7cd-06f3-426f-ad22-c08b0a8369cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>21e93d80-71de-463f-a00d-606724193987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-xa1darhv5rqs</value>
      <webElementGuid>b1b07577-86ae-4c00-9d65-374ef5de2d19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b59478e0-80ae-4c51-aaf1-282860f4129f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>d096f724-84be-4ac5-a2bf-f4b764aada46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>51db095b-e057-4a60-8cac-ac46c888c512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g-recaptcha&quot;)/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>7e605270-23ac-4943-8250-3a8fdd86bb72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-xa1darhv5rqs']</value>
      <webElementGuid>43997fbd-ec91-4d40-8877-57b7254e6d7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='g-recaptcha']/div/div/iframe</value>
      <webElementGuid>30fe3350-80fb-4838-8f9a-754c5f61fef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>54aade4c-3f27-4333-83bb-d7b1f96494d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LfiRzcaAAAAAF18-SQqrsovqK5dd4V8T1rgfpyC&amp;co=aHR0cHM6Ly93d3cuam9ic3RvZGF5LndvcmxkOjQ0Mw..&amp;hl=en&amp;v=IqA9DpBOUJevxkykws9RiIBs&amp;size=normal&amp;cb=o01wiuvb0spf' and @name = 'a-xa1darhv5rqs']</value>
      <webElementGuid>c58d90b7-ab45-4d31-a51f-187b028aa052</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
