<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Confirm My Choices_c-xa1darhv5rqs</name>
   <tag></tag>
   <elementGuidId>d30c950a-4ec8-4e7a-ab36-a8a30e022faf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;c-xa1darhv5rqs&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='c-xa1darhv5rqs']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>57d7b145-e905-40a2-aa59-4911145a9c84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>recaptcha challenge expires in two minutes</value>
      <webElementGuid>ec0de82a-78c2-4812-98b3-aaf07a658eaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/bframe?hl=en&amp;v=IqA9DpBOUJevxkykws9RiIBs&amp;k=6LfiRzcaAAAAAF18-SQqrsovqK5dd4V8T1rgfpyC</value>
      <webElementGuid>d103297f-4e9a-4c86-9fef-3d6500d3a984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>c-xa1darhv5rqs</value>
      <webElementGuid>c8519699-5c7f-4205-be09-06f209c57ccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e8486bcf-5eaa-44aa-aee6-d7d64ab2e0ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>733a6a00-ef40-4f26-849d-446407a467ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>9f6ebf30-9ef7-48fc-9502-82c1d0fddfd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;candidate-login&quot;]/div[8]/div[4]/iframe[1]</value>
      <webElementGuid>c40fdd14-043d-4c68-a5b6-34091534e4e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='c-xa1darhv5rqs']</value>
      <webElementGuid>ce8e9062-cc21-488f-8401-60db0128a8a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/iframe</value>
      <webElementGuid>329bd1d8-7982-4daa-bc89-eb752ebe945f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'recaptcha challenge expires in two minutes' and @src = 'https://www.google.com/recaptcha/api2/bframe?hl=en&amp;v=IqA9DpBOUJevxkykws9RiIBs&amp;k=6LfiRzcaAAAAAF18-SQqrsovqK5dd4V8T1rgfpyC' and @name = 'c-xa1darhv5rqs']</value>
      <webElementGuid>188a438f-a46f-4ae5-adf5-71b438b04427</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
