<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_stairs_rc-image-tile-33</name>
   <tag></tag>
   <elementGuidId>5d5ca562-8932-4a36-9621-d33cf1148f22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[3]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>652e6db2-20ee-4b20-9be0-c9012aee785a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>608456f6-2390-407f-8405-e5a8d721c142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AL8dmw9lLXUIyWewZJT8SgD-pknF8vpbqh-26vPk4zwoDQkwOfXzOBCaAAQ_qL2CC1wORQA8-_572R8zPByB4An4HsG4qukrtb0yNFuUfcQN3dlo00vdAQKZeO1UD29oDjRw-StPhE4TYukKVJSPt_Qpk-PQpTeAVF13kwWidu7CNp5sCAfpbLAvC1XAdMalDjp776GcIp_J&amp;k=6LfiRzcaAAAAAF18-SQqrsovqK5dd4V8T1rgfpyC</value>
      <webElementGuid>391fd4ec-67e1-48fa-b5ac-e0cd795ea2cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>9988e77e-8ebf-4589-ad77-67ee3d058bca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/CreateResume/Page_Login to Jobstoday.world - Create Resu_ef8a51/iframe_Confirm My Choices_c-xa1darhv5rqs</value>
      <webElementGuid>0ebb731c-1326-464c-803f-7890dd5bbdb1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[3]/div/div/img</value>
      <webElementGuid>6b02c6af-dabb-404c-9b47-94771d2627eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AL8dmw9lLXUIyWewZJT8SgD-pknF8vpbqh-26vPk4zwoDQkwOfXzOBCaAAQ_qL2CC1wORQA8-_572R8zPByB4An4HsG4qukrtb0yNFuUfcQN3dlo00vdAQKZeO1UD29oDjRw-StPhE4TYukKVJSPt_Qpk-PQpTeAVF13kwWidu7CNp5sCAfpbLAvC1XAdMalDjp776GcIp_J&amp;k=6LfiRzcaAAAAAF18-SQqrsovqK5dd4V8T1rgfpyC')])[3]</value>
      <webElementGuid>3c00f573-27e3-4fb3-9b59-f9e11c703053</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/div/img</value>
      <webElementGuid>7ed0b295-8c21-4539-b1f5-177a127076d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AL8dmw9lLXUIyWewZJT8SgD-pknF8vpbqh-26vPk4zwoDQkwOfXzOBCaAAQ_qL2CC1wORQA8-_572R8zPByB4An4HsG4qukrtb0yNFuUfcQN3dlo00vdAQKZeO1UD29oDjRw-StPhE4TYukKVJSPt_Qpk-PQpTeAVF13kwWidu7CNp5sCAfpbLAvC1XAdMalDjp776GcIp_J&amp;k=6LfiRzcaAAAAAF18-SQqrsovqK5dd4V8T1rgfpyC']</value>
      <webElementGuid>73637659-7f6e-41ae-86bf-78dbcee7143d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
