<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select</name>
   <tag></tag>
   <elementGuidId>eb324d88-bdff-4e9b-9486-a0eb39399ca8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.b-package-box__btn-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//li/div/form/button)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7683f6e1-9ae8-4d10-8eb5-750f569150af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>b-package-box__btn-text</value>
      <webElementGuid>df17f5f1-f75b-458f-ad75-0d0477cae576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>1e0a5bc3-189b-48a6-b2eb-6a92df5c4849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;package_item_403&quot;)/div[@class=&quot;b-package-box&quot;]/form[1]/button[@class=&quot;b-package-box__btn&quot;]/span[@class=&quot;b-package-box__btn-text&quot;]</value>
      <webElementGuid>72983547-ee43-4766-9f10-ef83369d924f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='package_item_403']/div/form/button/span</value>
      <webElementGuid>dd3c705f-f93f-4191-9f9f-600f9f2f180f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jobs Available:'])[3]/following::span[2]</value>
      <webElementGuid>b1b0aefc-eeda-4958-9a83-ddd7bc0cf8ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jobs Posted:'])[3]/following::span[4]</value>
      <webElementGuid>8d5a41f1-10ba-4cf4-ada3-96de6e438ae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Starter'])[1]/preceding::span[1]</value>
      <webElementGuid>68bdfc84-aa2a-4ccd-a41f-6f3ccbeef37e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Package ID:'])[4]/preceding::span[1]</value>
      <webElementGuid>e1f053bd-5a35-4c4e-bad3-3059e088fb3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select']/parent::*</value>
      <webElementGuid>7746064a-9ad5-4c72-83ad-dc6b07fdba40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button/span</value>
      <webElementGuid>6e184845-f197-4345-b2d4-99cc511f0d09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>d09d43f5-ce73-41f9-a71d-1c211820d909</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
