<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select</name>
   <tag></tag>
   <elementGuidId>eb324d88-bdff-4e9b-9486-a0eb39399ca8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.b-package-box__btn-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(@class,'button-buy-onetime-starter')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b93e1962-ac60-4773-8a4d-82c978c25168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>b-package-box__btn-text</value>
      <webElementGuid>c1c6cb52-5289-4c88-b73b-20a56a01163c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>756562f8-657a-4ed8-8753-8737e850320d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;package_item_403&quot;)/div[@class=&quot;b-package-box&quot;]/form[1]/button[@class=&quot;b-package-box__btn&quot;]/span[@class=&quot;b-package-box__btn-text&quot;]</value>
      <webElementGuid>00123268-62a6-4cc4-a4cd-b542b9b6c5e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='package_item_403']/div/form/button/span</value>
      <webElementGuid>935a9d89-5986-4db9-869d-fb6cf124fa8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jobs Available:'])[3]/following::span[2]</value>
      <webElementGuid>8bc90fe7-091b-4f07-b403-4ea1e18f2b03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jobs Posted:'])[3]/following::span[4]</value>
      <webElementGuid>cb397d95-4abf-4bf8-b064-c45432825f86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Starter'])[1]/preceding::span[1]</value>
      <webElementGuid>df3e81e6-db6d-456a-bedb-4e2642e6ba4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Package ID:'])[4]/preceding::span[1]</value>
      <webElementGuid>59203bd3-6b17-4244-834e-e87595da5032</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select']/parent::*</value>
      <webElementGuid>2b99ac37-100c-4484-9db4-bdabbf0670a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button/span</value>
      <webElementGuid>ed58ccca-55d6-40d7-8471-f1961336ec40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>fcecb80d-8e06-4126-abbd-92e5481a9b3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
