<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select</name>
   <tag></tag>
   <elementGuidId>eb324d88-bdff-4e9b-9486-a0eb39399ca8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.b-package-box__btn-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;package_item_369&quot;]/div/form/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3bf4cae4-5dc7-472f-8f7b-73ea4d7bce07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>b-package-box__btn-text</value>
      <webElementGuid>f5262127-aca2-49e0-85ec-178980bec680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>69292a65-3189-45b7-895f-ccb87678f4b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;package_item_403&quot;)/div[@class=&quot;b-package-box&quot;]/form[1]/button[@class=&quot;b-package-box__btn&quot;]/span[@class=&quot;b-package-box__btn-text&quot;]</value>
      <webElementGuid>7279d838-bf72-4fd3-98fb-962af5d83f69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='package_item_403']/div/form/button/span</value>
      <webElementGuid>51dbf0e8-95d1-407e-b367-e99e4b7b309c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jobs Available:'])[3]/following::span[2]</value>
      <webElementGuid>89571617-5abb-4ecd-b3c2-3e2e225d52ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jobs Posted:'])[3]/following::span[4]</value>
      <webElementGuid>4aed8285-e02d-4e22-be73-3b10d8f29ca7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Starter'])[1]/preceding::span[1]</value>
      <webElementGuid>a629b2fe-cbba-45ad-8a11-98894697e692</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Package ID:'])[4]/preceding::span[1]</value>
      <webElementGuid>4c6c9c4d-0955-4744-9141-272a0078d0b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select']/parent::*</value>
      <webElementGuid>9e8b9548-0f79-4161-a997-e07818ba4d14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button/span</value>
      <webElementGuid>13fc1b39-e610-43c7-8ac0-b9eea8cc48ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>51390e52-1bae-4288-9d1a-7650663c1020</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
