<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_City  Country_input_city_country</name>
   <tag></tag>
   <elementGuidId>51f05873-e8e8-4015-9057-f9f897451932</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='location']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#location</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>74d97271-3baa-49ea-abb1-4ff791a21340</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>location</value>
      <webElementGuid>65e6e00c-c1ef-4406-86a6-7f5fe07aaa51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>19981bc8-3d0f-402f-9dc7-8af3f60f8784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input_city_country</value>
      <webElementGuid>db98c2f5-2546-4f2f-b77d-ead17a22fcf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>City &amp; Country</value>
      <webElementGuid>9543257a-1a51-4bfc-bb13-ce91a5a9e5ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-field pac-target-input</value>
      <webElementGuid>7fa96763-dc04-4875-bbce-0c407690bffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f1da2b52-40fc-4614-b802-009290803897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;location&quot;)</value>
      <webElementGuid>8378ce97-41b1-49eb-9cf7-7575c7e9be76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='location']</value>
      <webElementGuid>43b7789c-496e-41c9-9fed-47c18c892218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-checkout']/div/div/div/div/div[3]/div[4]/div[2]/input</value>
      <webElementGuid>308baac0-854b-437a-98cc-aa3cfb9f5068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/input</value>
      <webElementGuid>e725a1e6-cc70-48cf-a5eb-74d76c497c21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'location' and @type = 'text' and @name = 'input_city_country' and @placeholder = 'City &amp; Country']</value>
      <webElementGuid>874da131-0990-43b5-80b0-71f22d9706a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
