<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_No</name>
   <tag></tag>
   <elementGuidId>b5fc6758-7126-4ac5-84d3-94c10b5b4df4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//fieldset[@id='myform-p-0']/div/div/div[2]/div[6]/div/label[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.add-position-information > div.form-group.company-contact-detail > div.custom-checkbox > label:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>3ce21960-7bb9-4224-91e9-a9fcab1dd924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>radio_button-08</value>
      <webElementGuid>33225d18-d049-441b-8ca2-24792231ecbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No</value>
      <webElementGuid>2a0d9e4e-83c7-43cf-b955-05d10d3831e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myform-p-0&quot;)/div[@class=&quot;form-tab&quot;]/div[@class=&quot;tab-content current&quot;]/div[@class=&quot;add-position-information&quot;]/div[@class=&quot;form-group company-contact-detail&quot;]/div[@class=&quot;custom-checkbox&quot;]/label[2]</value>
      <webElementGuid>628be751-eb34-477c-9d8f-26727c0ffe1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='myform-p-0']/div/div/div[2]/div[6]/div/label[2]</value>
      <webElementGuid>26a461cd-9055-45d6-b5dc-281041812492</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[3]/following::label[1]</value>
      <webElementGuid>4706a7b9-fd21-45e2-a2ca-f8471b3c490b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select this option to ask the candidate for address, phone number, date of birth.'])[1]/following::label[2]</value>
      <webElementGuid>141b80d1-583d-45e5-99b5-410dff871d49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select application process'])[1]/preceding::label[1]</value>
      <webElementGuid>8d6051f2-59d2-4b11-bbaf-31e9e155e83a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/label[2]</value>
      <webElementGuid>4dce2c07-0020-4d1a-b834-4247a560873a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'No' or . = 'No')]</value>
      <webElementGuid>9ec565c1-ae62-47a8-acff-ab75aaf2bf3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
