<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select number</name>
   <tag></tag>
   <elementGuidId>62abef26-bed8-4969-a6ae-bd6f4625ec69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-input_number_of_employee-ld-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-input_number_of_employee-ld-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>93bae32b-9255-4dc2-9158-06946befac2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>209cdb7d-a6bc-446f-877d-7b70a24e6bef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-input_number_of_employee-ld-container</value>
      <webElementGuid>a250bb28-c30c-4524-9239-73300b823811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>d7eaa37f-4b20-402c-bc6c-230a2307915a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>24b67f43-1394-4759-8f37-49403f779c55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select number</value>
      <webElementGuid>103b4181-61a0-4d77-8ed9-8f4a7a61416e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-input_number_of_employee-ld-container&quot;)</value>
      <webElementGuid>07d0b443-b5c6-4d2a-8919-6b647a4ea06a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-input_number_of_employee-ld-container']</value>
      <webElementGuid>b383d04f-6091-4a8e-a4e7-5b956e8e3b2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-checkout']/div/div/div/div/div[3]/div[7]/div[2]/span/span/span/span</value>
      <webElementGuid>265a5008-e5c9-45b7-80a6-ac67ce153fb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='German'])[2]/following::span[7]</value>
      <webElementGuid>582dd8a4-d69f-45ad-9593-d2fd11d66263</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registration Error'])[1]/preceding::span[5]</value>
      <webElementGuid>bd244ed3-60ea-42e7-941a-d9a6c919855b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/span/span/span</value>
      <webElementGuid>e1d133ff-0e6b-471d-9b68-7f088c076400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-input_number_of_employee-ld-container' and (text() = 'Select number' or . = 'Select number')]</value>
      <webElementGuid>e990f9dc-1ca8-4260-b876-976f595851c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
