<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select communication language</name>
   <tag></tag>
   <elementGuidId>3e309414-ac13-483c-a0f3-abde6f240f54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-input_communication_language-ha-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-input_communication_language-ha-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>620dbc33-5343-4a87-a52b-4b2a77e210af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>c8cb1b22-7df2-4967-86d0-9e255b6727c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-input_communication_language-ha-container</value>
      <webElementGuid>ef7d5d01-5964-44f6-b887-5cf7f4417945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>438f8efb-e456-4a3e-9a6a-c00b0ed3e6b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fd95e1cd-0a18-4291-b4f5-a98c966ac2af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select communication language</value>
      <webElementGuid>41c3400e-d2c4-4438-8acf-3e6978c048e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-input_communication_language-ha-container&quot;)</value>
      <webElementGuid>096c5153-a57f-4592-a921-6dc66532e859</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-input_communication_language-ha-container']</value>
      <webElementGuid>f02c8b71-ae1f-4458-b217-e10545d98f0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-checkout']/div/div/div/div/div[3]/div[7]/div/span/span/span/span</value>
      <webElementGuid>c4037787-176f-4f2f-a9f7-d49b25e8728a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administration'])[2]/following::span[8]</value>
      <webElementGuid>9940fff1-d2b8-46f0-8f3f-46cadc42e614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/span/span/span/span</value>
      <webElementGuid>af4010e4-2e86-41e6-93ee-5a519c5b3df4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-input_communication_language-ha-container' and (text() = 'Select communication language' or . = 'Select communication language')]</value>
      <webElementGuid>4dd641dd-04ea-45b3-8b8f-a275824c7f18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
