<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Enter a short Job description, it _305c38</name>
   <tag></tag>
   <elementGuidId>c5d7b7b2-869a-446e-9761-d36d1bbe883a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#short_description</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;short_description&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>13c06c69-9575-4da4-b824-e4cb28cf9347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d283c901-732f-4968-a6f1-372f95147db9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>row</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>3616cd2a-b985-42e6-9f8f-c170cb3a531d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>short_description</value>
      <webElementGuid>bc0b0dd0-aa85-4e15-9146-b50f601b2bfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>short_description</value>
      <webElementGuid>ad8a1526-13dc-4112-8971-9e43f880d7c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Job description (min 50 characters)</value>
      <webElementGuid>a0f79947-afc5-4ade-9502-934abd68decb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;short_description&quot;)</value>
      <webElementGuid>51d08699-e69f-4d52-98a9-10a008d910df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='short_description']</value>
      <webElementGuid>01053777-cb81-49b7-803b-f5597aa47c98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='myform-p-0']/div/div/div/div[7]/div/textarea</value>
      <webElementGuid>f8faa7b8-9f31-4271-a705-89b5351454e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/textarea</value>
      <webElementGuid>4251cf11-1cb5-4e85-941e-3177ed22e299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'short_description' and @id = 'short_description' and @placeholder = 'Enter Job description (min 50 characters)']</value>
      <webElementGuid>9beee162-4dc5-4510-8a45-59180a4ab7c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
