<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Password_a-8lych6gs1v9w</name>
   <tag></tag>
   <elementGuidId>9dac09cc-bff3-4107-9ac3-bd68c90ef3f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-8lych6gs1v9w']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-8lych6gs1v9w&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>a2af3be0-a299-47f6-bf44-f76cdd54556f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>5c7f813b-b1b9-4e80-9df1-947a10ee31e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>4ab5ae9f-bafb-4733-93cb-be5426f99cbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>10c552cc-7aec-4a8d-8171-224d4f224fe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>9dc96b0b-fb87-4b1c-9625-db3295d22467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-8lych6gs1v9w</value>
      <webElementGuid>583a5d15-2c78-4f19-be5d-65052b1f7b12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2b94631a-bcca-4518-867c-e6fd7363ce10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>3510c784-adcb-484a-bf57-5e2a954ba939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox</value>
      <webElementGuid>cf4afbc9-ab92-4d1f-8216-86887b120fa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LfiRzcaAAAAAF18-SQqrsovqK5dd4V8T1rgfpyC&amp;co=aHR0cHM6Ly93d3cuam9ic3RvZGF5LndvcmxkOjQ0Mw..&amp;hl=en&amp;v=pxZcVU8Dk73FyvFvdCgp2MSG&amp;size=normal&amp;cb=gy0emyam1vzr</value>
      <webElementGuid>157bbc6f-50fc-4870-825e-e06a5c915920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g-recaptcha&quot;)/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>d99111c5-388a-4957-b757-cd1be9378c69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-8lych6gs1v9w']</value>
      <webElementGuid>bbb2b3de-200f-462d-ab5a-3b0d9cf6be39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='g-recaptcha']/div/div/iframe</value>
      <webElementGuid>0887ca8c-f7b0-4e2e-ac35-6a6aedca782d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>1fd6bd40-ef6f-4786-8cd8-0f27f1d15b8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-8lych6gs1v9w' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LfiRzcaAAAAAF18-SQqrsovqK5dd4V8T1rgfpyC&amp;co=aHR0cHM6Ly93d3cuam9ic3RvZGF5LndvcmxkOjQ0Mw..&amp;hl=en&amp;v=pxZcVU8Dk73FyvFvdCgp2MSG&amp;size=normal&amp;cb=gy0emyam1vzr']</value>
      <webElementGuid>b096518a-bc92-4576-abe5-efdba39cb57b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
