<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>countryDropDown</name>
   <tag></tag>
   <elementGuidId>e0203398-3852-4f3e-b7dc-84a99ed77f36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[name='countries[]']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/div[3]/div/ul/li/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8705598c-5217-4fea-a747-13d660b3da84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/images/icon/search-Icon.svg</value>
      <webElementGuid>8bb9074b-e287-43d4-b67e-c09854635643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;header-menu&quot;]/div[@class=&quot;vertical-menu left--menu mobile-hidden&quot;]/ul[@class=&quot;display--flex&quot;]/li[1]/a[@class=&quot;display--flex align-item--center&quot;]/img[1]</value>
      <webElementGuid>f8bbc2c8-d5ea-48c7-8f5c-ac2aa13cfd29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/div[3]/div/ul/li/a/img</value>
      <webElementGuid>1219c154-8661-4416-aa7c-2eb5f8158ff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/ul/li/a/img</value>
      <webElementGuid>02822c57-08ac-4ee0-ad5e-1094b2e9b2be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/images/icon/search-Icon.svg']</value>
      <webElementGuid>8412b1c3-32a1-4a5b-8916-423a23e73494</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
