<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>e0203398-3852-4f3e-b7dc-84a99ed77f36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.display--flex > li > a.display--flex.align-item--center > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/div[3]/div/ul/li/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>57a837d0-fdab-4be4-8e0e-2314a2c2f475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/images/icon/search-Icon.svg</value>
      <webElementGuid>17fea201-d973-4775-9771-9af37cf7d8fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;header-menu&quot;]/div[@class=&quot;vertical-menu left--menu mobile-hidden&quot;]/ul[@class=&quot;display--flex&quot;]/li[1]/a[@class=&quot;display--flex align-item--center&quot;]/img[1]</value>
      <webElementGuid>e59f59a1-efc9-439f-be22-52a9eb044f1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/div[3]/div/ul/li/a/img</value>
      <webElementGuid>c94bb093-a463-475c-b95d-9f83b7af2393</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/ul/li/a/img</value>
      <webElementGuid>af6a1e4e-b5f2-4820-8b15-0d0054865f5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/images/icon/search-Icon.svg']</value>
      <webElementGuid>c29a7cd7-9259-4036-8078-be69d17d894a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
