<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select File_cropper-face cropper-move</name>
   <tag></tag>
   <elementGuidId>b6a9b8d4-e3c9-426e-8078-5ad892c6c534</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;fileInputImage&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.cropper-face.cropper-move</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8b15a36e-5c94-4dfa-b769-b8bce62dd087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cropper-face cropper-move</value>
      <webElementGuid>d872c5b7-6f2f-4bc1-abcf-1bea207a2cf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select-picture-modal&quot;)/div[@class=&quot;crop-area-main&quot;]/div[@class=&quot;crop-area&quot;]/div[@class=&quot;image-crop-section&quot;]/div[@class=&quot;cropper-container cropper-bg&quot;]/div[@class=&quot;cropper-crop-box&quot;]/span[@class=&quot;cropper-face cropper-move&quot;]</value>
      <webElementGuid>520586ef-2990-463b-8959-bd0551188e20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='select-picture-modal']/div[2]/div/div[2]/div/div[3]/span[5]</value>
      <webElementGuid>92f771c9-6af5-4143-b8b1-4101436db770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[5]</value>
      <webElementGuid>4f340171-70ea-4cc6-b8fc-f9bfc3e0c540</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
