<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Manager, Data Integration, Research IT Data Engineering</name>
   <tag></tag>
   <elementGuidId>7aa055f5-73fe-41e6-8f5a-5ddd6c30ac1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.view-job-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='results']/div[3]/div/div[2]/h3/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1b391c04-96e2-410b-bd31-4cbcb9e558b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en/job/es/da92d04661815f91eeb8dd8275c8505d/</value>
      <webElementGuid>43266202-2f81-4291-b556-1eee0a4bfe4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>f2bb3ad1-03d7-4662-aa7a-64c8d20fa5f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>view-job-title</value>
      <webElementGuid>a4f57507-a7d7-45e3-b36d-91fc1947be67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Manager, Data Integration, Research IT Data Engineering            </value>
      <webElementGuid>6e4af9aa-541d-4910-a392-2d63a1f134cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;results&quot;)/div[@class=&quot;job--list display--flex flex--wrap&quot;]/div[@class=&quot;single--block display--flex&quot;]/div[@class=&quot;job--info&quot;]/h3[@class=&quot;job--title margin-0&quot;]/a[@class=&quot;view-job-title&quot;]</value>
      <webElementGuid>180e0c68-86f9-4e9a-86e1-075c0bb73342</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='results']/div[3]/div/div[2]/h3/a</value>
      <webElementGuid>4a46e814-cb08-40c2-a262-938284db5a05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Manager, Data Integration, Research IT Data Engineering')]</value>
      <webElementGuid>4b8dbe46-0e77-4d5d-9cb8-f686ea956fc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bristol Myers Squibb'])[1]/following::a[1]</value>
      <webElementGuid>1cc49d1e-7a93-4d6c-baf5-15a1fbc0de4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oldest Jobs'])[2]/following::a[1]</value>
      <webElementGuid>3d858828-ba79-4abf-9c26-0217b0d15704</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Job'])[1]/preceding::a[1]</value>
      <webElementGuid>809f9038-9726-4aba-acaf-6b65bfda4a37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Manager, Data Integration, Research IT Data Engineering']/parent::*</value>
      <webElementGuid>2150cbdc-2413-4cb2-b889-968186a77534</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/en/job/es/da92d04661815f91eeb8dd8275c8505d/')]</value>
      <webElementGuid>d8fb5546-7e8d-4e87-ad5f-5b2f256fda1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/a</value>
      <webElementGuid>29bc2240-115d-4707-aa6b-a5306923b1b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/en/job/es/da92d04661815f91eeb8dd8275c8505d/' and (text() = '
                Manager, Data Integration, Research IT Data Engineering            ' or . = '
                Manager, Data Integration, Research IT Data Engineering            ')]</value>
      <webElementGuid>5374bce7-83c1-4ce5-8458-4ac121eeed15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
