<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Find employees from around the world_location</name>
   <tag></tag>
   <elementGuidId>aef45b4c-b9b5-4cb3-86c0-60d5ee601a04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#location</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='location']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>11461aac-00c9-4d79-842e-68eadfc5bb97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5c3a515f-5b7f-4797-9c79-fb3f49f49dd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Job locations</value>
      <webElementGuid>aef8c680-8f6c-4c3e-90ca-9c9d21a42bac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>location</value>
      <webElementGuid>475534ca-7a3e-4881-9b6d-ac88cacf3c2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>location</value>
      <webElementGuid>d38fd114-1e3f-4814-953c-becc10396a78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Giza, Egypt</value>
      <webElementGuid>f6c32a62-3baa-4640-a36a-a998e79a9078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pac-target-input</value>
      <webElementGuid>b7bde4ca-cee3-4217-801b-de683b9aed38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ed8fc72f-ea08-4da5-82dc-5960f81a61cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;location&quot;)</value>
      <webElementGuid>86a208a6-0aa2-47d5-ba4b-921182743e4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='location']</value>
      <webElementGuid>43d7e561-0be8-40b5-a431-9943782d1a1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='search']/div[2]/input</value>
      <webElementGuid>b194c2cc-771c-4227-8e66-750151a660f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>dc9cf532-d482-4616-9bcc-03ffbfbec9e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Job locations' and @id = 'location' and @name = 'location']</value>
      <webElementGuid>cb13f836-9c92-4686-87d9-0b41bd54ee04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
