<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Find employees from around the world_keywords</name>
   <tag></tag>
   <elementGuidId>5d305a25-570a-4eb2-91f0-6f85eff9a22c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#keywords</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='keywords']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f02281c0-4ee8-4e18-9f31-a03e25c4ed6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cf2cab3d-ca83-46db-9733-f74244f209d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search Jobs</value>
      <webElementGuid>dcd3a4c4-a910-4a6f-a39a-b4c9d9e1c3f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>keywords</value>
      <webElementGuid>3ec7f70a-3038-4ae3-9abd-e5c1cd0caddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>keywords</value>
      <webElementGuid>b21b401e-4ed4-409e-bb76-84926d95a8a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;keywords&quot;)</value>
      <webElementGuid>c791d20b-3518-4b08-b832-d85375f614bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='keywords']</value>
      <webElementGuid>d7d48773-d4a7-4df2-81bd-ed82e7f2d6f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='search']/div/input</value>
      <webElementGuid>9b6e52d3-10f8-49e2-b2e4-ba0de6d59730</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>adbd5cfa-228e-41ea-95a3-ffca0561a6a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search Jobs' and @id = 'keywords' and @name = 'keywords']</value>
      <webElementGuid>d40fed07-9f92-4e16-a755-ba40c1b71c0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
