<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Subscribe</name>
   <tag></tag>
   <elementGuidId>8aba689f-0b18-4f47-832e-bbeb8d6a208f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>form > [type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>form > [type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a4acdfbf-b7e9-4261-b7a2-e453e2ed934e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Subscribe</value>
      <webElementGuid>eeca7d2b-bb44-42c6-9d9f-e372bacc42ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;index--page&quot;]/footer[@class=&quot;foooter&quot;]/div[@class=&quot;footer-wrapper&quot;]/div[@class=&quot;footer-main&quot;]/div[@class=&quot;news-letter&quot;]/div[@class=&quot;news-letter-section&quot;]/form[@class=&quot;subscribe-form-footer2&quot;]/div[@class=&quot;submit--button&quot;]/button[1]</value>
      <webElementGuid>04ad8abb-100f-466b-92ed-ee843406f117</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Vacancies in Your Inbox'])[1]/following::button[1]</value>
      <webElementGuid>6a9de9f4-85ea-42e8-938b-85dd127d7e73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GDPR'])[1]/following::button[1]</value>
      <webElementGuid>6575861c-d17a-46b0-91f8-a1c2e53ca8c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Popular Jobs'])[2]/preceding::button[1]</value>
      <webElementGuid>f9b3f9fd-2853-4a66-ae22-828417bfe010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jobs by Industry'])[2]/preceding::button[1]</value>
      <webElementGuid>68c80906-84a9-4546-9541-d1cc855ac067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Subscribe']/parent::*</value>
      <webElementGuid>6839acd0-1447-4215-bab1-1d9bbac31427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/button</value>
      <webElementGuid>bd06c677-3f89-4891-a0d8-c0d9130850d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Subscribe' or . = 'Subscribe')]</value>
      <webElementGuid>4994558d-72d4-4b1b-a5d7-e9256e5eaf94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
